### ISSUE TITLE
Use new tagging system

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#1]
In order to update ZIM files to the [new tagging system](https://wiki.openzim.org/wiki/Tags), please make sure your scraper:

* <s>is using the lastest zimwriterfs (`1.3.5+` or `:latest` docker image). It supports new options and fixes important metadata (tags, favicon) and LZMA compression level.</s> not pertinent
* is including a `_category:xxx` tag (See [kiwix-tools#317](https://github.com/kiwix/kiwix-tools/issues/317))
* is including a tag for your content (ex: `Wikipédia`, `DirtyBiology`, etc.)
* is setting a proper `--name`.
* is using a proper `--flavour` (if relevant)
* is setting a `--scraper`.

**Comment by ikreymer** [comment]
@kelson42 Hm, is this the right place for this issue? This library is not a scraper, but will convert WARCs to ZIMs. This probably belongs elsewhere?

**Comment by kelson42** [comment]
@ikreymer It's is the right place, `warc2zim` should secure this is done properly.

**Comment by rgaudin** [comment]
Yes, I didn't mention it yesterday because that's not the focus right now but since warc2zim produces the ZIM, it is a *scraper* in the sense of our toolchain (zimfarm mostly).
So we'll have options on warc2zim to set the metadata and filename.

@kelson42 would we want an additional tag and/or category for zimit-created ZIMs ?

**Comment by ikreymer** [comment]
Ok, I was confused since we hadn't talked about this before and it was the first issue.. Yes, let me know what this tag/category metadata should look like..
