### ISSUE TITLE
Redirect problem found between 1.4.0 and 1.4.3

### ISSUE THREAD

**Issue by wsdookadr** [openzim/warc2zim#100]
While #94 was addressing an isolated case of HTTP 300 Multiple Choice, it seems the fix there has some side-effects.
With warc2zim 1.4.0 the redirects are working well, with 1.4.3 they're *always* redirecting to the live site.

To reproduce, there is a WARC attached to this issue, containing 3 web pages.
A good test page would be this one: http://localhost:8083/big/A/proofwiki.org/wiki/Asymptotic_Growth_of_Euler_Phi_Function
(assuming the ZIM is served on port 8083).

[r1.zip](https://github.com/openzim/warc2zim/files/9106269/r1.zip)

**Comment by rgaudin** [comment]
@wsdookadr, thank you for the report. Can you be more specific about expected and actual behavior?

I've tested this warc and can access said page:

<img width="1025" alt="Screen Shot 2022-07-18 at 11 14 33" src="https://user-images.githubusercontent.com/57929/179499831-a69f906a-4355-415b-a388-4e4f18c70010.png">

**Comment by wsdookadr** [comment]
> Can you be more specific about expected and actual behavior?

I've tried it again, I can't confirm it anymore. Probably something on my side related to browser cache.
