### ISSUE TITLE
Test output writable is unusable when not successful

### ISSUE THREAD

**Issue by Tbwan** [openzim/warc2zim#106]
I've installed warc2zim on an external hard drive, and everything installs fine using the instructions. 'warc2zim --help' works properly. However, on attempting to use it, I get the following error, shown below. I've retried it several times, and each time the tmp filename changes, obviously, but I'm unsure if this is a bug related to my setup, or if I'm doing something wrong?

warc2zim /input/instructables.warc --output /output --name instructables.zim -u http://www.instructables.com/

Traceback (most recent call last):
  File "/media/alex/deepstorage1/zimittesting/env/bin/warc2zim", line 8, in <module>
    sys.exit(warc2zim())
  File "/media/alex/deepstorage1/zimittesting/env/lib/python3.10/site-packages/warc2zim/main.py", line 818, in warc2zim
    warc2zim = WARC2Zim(r)
  File "/media/alex/deepstorage1/zimittesting/env/lib/python3.10/site-packages/warc2zim/main.py", line 246, in __init__
    with tempfile.NamedTemporaryFile(dir=self.output, delete=True) as fh:
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/output/tmp9479ws_0'

**Comment by kelson42** [comment]
@Tbwan Thank you for your question. I have assign the ticket to a colleague who will be able to help you. But are you sure `/output/` exists? is writable for your current user used to start `warc2zim`?

**Comment by Tbwan** [comment]
@kelson42 thanks for the quick reply. I created an output folder in the location I was running the command from, and I've ensured it has full read/write/create/delete permissions for all users (recursively for files inside as well.) 

-So, I'm running the command while in: /media/alex/deepstorage1/zimittesting/  
-And the output folder location is /media/alex/deepstorage1/zimittesting/output/

After your reply, I thought perhaps I need to list the full path, so I tried it with: 
`--output: /media/alex/deepstorage1/zimittesting/output` 
but that didn't work either.

**Comment by kelson42** [comment]
@Tbwan Can you please share the latest log?

**Comment by Tbwan** [comment]
Sorry for the "output:" confusion, I mistyped that. 

I have started over in a new location, off the external hard drive. I realized the external drive is NTFS formatted, and was worried that it might be messing with permissions. (My main hard drive is ext4.) Here are the steps I took, with many details for full clarity.

-I navigated via the GUI to the documents directory (home/alex/Documents)
-I placed my instructables.warc file in `home/alex/Documents`
-I opened a terminal and navigated to `home/alex/Documents`
-Installed warc2zim in `home/alex/Documents` following the directions on the readme.md
-I created an output folder at `home/alex/Documents/output`
-I enabled root, and ran `chmod -R 777 output/` to ensure absolutely anyone can do anything, anywhere in that directory.
-As root, I ran `source env/bin/activate`
-As root, I ran `warc2zim instructables.warc --output /output --name instructables.zim -u http://www.instructables.com/`

Here's the log:

Traceback (most recent call last):
  File "/home/alex/Documents/env/bin/warc2zim", line 8, in <module>
    sys.exit(warc2zim())
  File "/home/alex/Documents/env/lib/python3.10/site-packages/warc2zim/main.py", line 818, in warc2zim
    warc2zim = WARC2Zim(r)
  File "/home/alex/Documents/env/lib/python3.10/site-packages/warc2zim/main.py", line 246, in __init__
    with tempfile.NamedTemporaryFile(dir=self.output, delete=True) as fh:
  File "/usr/lib/python3.10/tempfile.py", line 698, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
  File "/usr/lib/python3.10/tempfile.py", line 695, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/usr/lib/python3.10/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/output/tmpiar_djvx'


Guess what fixed it? I changed the slash. I had just copied and pasted from the readme without much thought.
Instead of `--output /output` like the readme states, I used `--output output/` and now everything works well!

So I think the readme should be fixed or clarified, as the current readme gives the following example:
`warc2zim ./path/to/myarchive.warc --output /output --name myarchive.zim -u https://example.com/`

**Comment by kelson42** [comment]
@rgaudin we mostly need here a clear error.

**Comment by rgaudin** [comment]
Yes, the log should precede the test.

**Comment by jairajmahadev** [comment]
@rgaudin I would like to work on this issue. I tried writing the test inside a ```try-except```. This logs the error correctly but the ```logger.debug``` which I have written before the try-except block is not printing on the console.

**Comment by rgaudin** [comment]
`logger.debug` would print only with `--debug` flag I think.
