### ISSUE TITLE
Web sites with case-insensitive URLs can cause problems when converted to ZIM format with warc2zim

### ISSUE THREAD

**Issue by Jaifroid** [openzim/warc2zim#107]
This may be a platform limitation because the ZIM format doesn't deal well with case insensitivity, but I've come across a few cases where URLs written case-insensitively cannot access the equivalent article that is stored at a URL with different case, where the original web server is not case-sensitive.

A good example is  https://library.kiwix.org/viewer#developer.mozilla.org_en_all_2023-02/A/developer.mozilla.org/en-US/ . To reproduce: from the front page, without navigating elsewhere, hover over "References" in the menu and choose any entry. Kiwix Serve will fail to find the corresponding URL. Now navigate to another article (e.g. Web APIs under Featured Articles) and do the same (hover over References and choose a menu item). This time, the article will load.

The difference between the two is that in the first instance, the URL is presented with `en-us` (lowercase US) as part of its name, whereas in the second it is correctly specified with `en-US`.

Now, arguably, the scraper should store the underlying article twice, to avoid this issue, or should use the Header mechanism to redirect the former to the latter. However, the underlying WARC format can probably cope with case-insensitivity and economizes when storing the article, because the browser redirects to the same underlying article. The ZIM format, however, can't cope with this situation.

I'm including a kind of "fuzzy search" in Kiwix PWA that mostly finds such links, though not universally (without brute force, there is no way to use efficient binary search case-insensitively unless all URLs are sorted case-insensitively, e.g. converted to lowercase and sorted alphabetically).

Ideally, however, we'd have some safeguards in warc2zim for such situations.

**Comment by rgaudin** [comment]
See https://github.com/openzim/zimit/issues/171

**Comment by rgaudin** [comment]
The issue with this ZIM is that it was scoped so we didn't crawl boh URLs. I believe without the scope we would have redirects and this is fine. We relaunched it but scope was too wide (canceled it while it was crawling github 😅). We'll get there.

Now, without an actual problem to fix, this becomes just an optimization and I don't think it's worth the complexity and maintenance cost. Redirects are very lightweight IMO.

**Comment by Jaifroid** [comment]
Ah, OK, seems like I misdiagnosed the issue as being about case-(in)sensitivity rather than scope, or, rather, that there are mechanisms built in to the crawler to deal with such situations.  In which case, I'm happy to close (and sorry I had not seen the closed issue that raised this previously).

**Comment by rgaudin** [comment]
Well, it would work in this case because the webserver itself is case sensitive but there is a redirection from `en-us` to `en-US`. Should a server be case insensitive (maybe on a Windows OS?) and returning the same content on both URLs without a redirect, then indeed zimit would store article twice (and zimcheck would complain).

I believe this is a rare enough scenario… but who knows?

**Comment by Jaifroid** [comment]
Agree it's rare, but if the server uses redirection to deal with case-insensitive requests and normalizes the final URL, then Zimit should work as you say.

**Comment by Jaifroid** [comment]
It just occurred to me that this kind of issue could be avoided if the test of whether a particular URL is in-scope were made case-insensitive. This can easily be done by using the RegEx `i` flag when comparing the scope pattern to the URL to be scraped. Or else, use the Python equivalent of JS `localeCompare` which allows for case-insensitivity (amongst a wide range of options) -- maybe `casefold()` or simply convert both strings to lowercase with `.lower()` before doing the comparison. Sorry if this is obvious and not as easy to do as it seems at first sight.
