### ISSUE TITLE
Not all videos thumbs are loaded properly in lesfondamentaux.zim

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#11]
This is how the page "Respecter autrui" looks like for me with FF, kiwix-serve and lesfondamentaux.zim (only 3 video thumbs):
![image](https://user-images.githubusercontent.com/1029718/88561064-39cd0800-d02f-11ea-9157-030c2ee8ff47.png)

This is how it looks like online (5+ 5 video thumbs):
https://lesfondamentaux.reseau-canope.fr/discipline/instruction-civique-histoire-geographie/respecter-autrui.html

**Comment by kelson42** [comment]
Works now... weird. Lets keep the ticket open to see if this behaviour occurs again.

**Comment by ikreymer** [comment]
I was able to repro this once in FF.. Basically FF was stuck on loading and did not finish loading the page (The Refresh button remained at an X). I couldn't find any other error messages, so seems like some sort of FF weirdness..

**Comment by kelson42** [comment]
Closing for the moment as there is no clear actionnable and the impact is pretty limited.
