### ISSUE TITLE
More user-friendly messages when a Zimit ZIM cannot be opened

### ISSUE THREAD

**Issue by Jaifroid** [openzim/warc2zim#111]
We currently have the following [messages](https://github.com/openzim/warc2zim/blob/main/src/warc2zim/templates/load.js#LL10C62-L10C131), which are not very intuitive for many non-technical users:

1. This page must be loaded via an HTTPS URL to support service workers.
2. The requested URL can not be loaded because service workers are not supported here.
3. If you use Firefox in Private Mode, try regular mode instead.
4. If you use Kiwix-Serve locally, replace the IP in your browser address bar with <code>localhost</code>.

I suggest changing these to:

1. This type of ZIM needs to install a Service Worker, which can only be done in secure contexts. This means that you need to ensure the URL begins with https:// instead of http://. Try changing the protocol to https in you browser address bar.
2. This type of ZIM needs to install a Service Worker, which can only be done in secure contexts. If you are accessing this ZIM in Kiwix Desktop, unfortunately the web view does not yet support Service Workers. However, you can instead use the built-in server feature to view this ZIM archive. Click the three dots at the top right of the Kiwix Desktop app, and turn on "Local Kiwix Server". Then click "Open in browser".
3. Note that if you are using Firefox in Private Mode, then this disables Service Workers as a security measure. Please try opening the Kiwix Serve home page in normal mode instead.
4. If you are accessing the Kiwix Serve home page from a local IP address like http://127.0.0.1, this might not work in all browsers. Try changing the browser address to `http://localhost:[port]` instead (replace `[port]` with the port number shown in Kiwix Serve startup configuration).

**Comment by Jaifroid** [comment]
I also think that the title "ERROR" (see screenshot) could be changed to:

## Troubleshoot reading Zimit-based archives

![image](https://github.com/openzim/warc2zim/assets/4304337/eb56484a-4232-4b64-9215-b50a63b2011c)

**Comment by kelson42** [comment]
What should we do with that isue. I guess all these messages have been removed in 2.0?

**Comment by rgaudin** [comment]
Indeed
