### ISSUE TITLE
Use scraperlib3.1

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#112]
In order to properly set all metadata. Should there be no illustration, [libkiwix's missing illustration](https://github.com/kiwix/libkiwix/blob/main/static/skin/index.css#L230) one should be used

**Comment by kelson42** [comment]
@rgaudin @benoit74 I don't know exactly what this implies, but it is necessary to have the most recent version for Zimit2.

**Comment by rgaudin** [comment]
w2z is already using scraperlib 3.1.1 but we'll need to update to latest version with clones once it gets released
