### ISSUE TITLE
 libzim/libwrapper.cpp:175:32: error: ‘Lzma’ is not a member of ‘zim::Compression’

### ISSUE THREAD

**Issue by kashortiexda** [openzim/warc2zim#114]
I am using python3.11 in a virtual environment. I do have lzma. 
I have tried to install the .whl and also in Terminal with.. 
pip install -U warc2zim 
but keep getting the below error: ‘Lzma’ is not a member of ‘zim::Compression’
Have tried on MacOS, Linux Ubuntu and Fedora.
Please advise (do I need a lower version of Python ?)

creating build/temp.linux-x86_64-cpython-311/libzim
      gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Ilibzim -I/home/paulhurst/Python-3.11.3/env/include -I/usr/local/include/python3.11 -c libzim/libwrapper.cpp -o build/temp.linux-x86_64-cpython-311/libzim/libwrapper.o -std=c++11 -Wall -Wextra
      libzim/libwrapper.cpp: In function ‘zim::Compression comp_from_int(int)’:
      libzim/libwrapper.cpp:175:32: error: ‘Lzma’ is not a member of ‘zim::Compression’
        175 |       return zim::Compression::Lzma;
            |                                ^~~~
      error: command '/usr/lib64/ccache/gcc' failed with exit code 1
      [end of output]

**Comment by kelson42** [comment]
Hmmm, looks like a part of the dependency is too old (maybe python-libzim) because indeed we don't allow to compress using lzma since many libzim releases.

@rgaudin would know better.

**Comment by rgaudin** [comment]
Installing latest warc2zim release gives you a fairly old libzim (1.1.1) which had no binary for Python 3.11 (3.10 max).
I'd suggest you use main branch which pulls libzim 2.1.0 which has py311 binary.

```sh
pip install warc2zim@git+https://github.com/openzim/warc2zim#egg=warc2zim
```

**Comment by kelson42** [comment]
I have created a ticket in an attempt to speed-up the release #116
