### ISSUE TITLE
Zim to xml

### ISSUE THREAD

**Issue by TeckboyAj** [openzim/warc2zim#118]
Hello, I want to ask you is this possible to convert the zim file into XML file without losing the content of the zim file?

**Comment by rgaudin** [comment]
Zim is just a packaging format that holds entries (can be regarded as files).
Since you can access all entries you could turn it all into whatever format.
Question is too broad to give a more answer I'm afraid

**Comment by TeckboyAj** [comment]
So how we can convert it into xml file. So you have any idea? I tried to use kiwixtools and other but didn't get any result from there?

**Comment by rgaudin** [comment]
zim-tools has a zimdump that extract all entries to file system. libzim (and it's python wrapper) are another possibility to retrieve the articles
