### ISSUE TITLE
Fragment-including fragment cant be found

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#124]
This needs to be checked but a zimit crawl with URL https://www.biblegateway.com/versions/English-Standard-Version-ESV-Bible/#booklist resulted in a warc2zim error:

```
KeyError: 'Unable to find WARC record for main page: https://www.biblegateway.com/versions/English-Standard-Version-ESV-Bible/#booklist, aborting'
```

I imagine there is no such WARC record but one for `/versions/English-Standard-Version-ESV-Bible/` wich is the one that should be checked-for and used.

**Comment by benoit74** [comment]
Command was
```
zimit --include=https://www.biblegateway.com/passage/ --url=https://www.biblegateway.com/versions/English-Standard-Version-ESV-Bible/#booklist --name=www.biblegateway.com_399ad441 --zim-file=www.biblegateway.com_399ad441.zim --userAgentSuffix=Youzim.it+ --sizeLimit=4294967296 --timeLimit=7200 --output=/output --statsFilename=/output/task_progress.json --adminEmail=contact+zimfarm@kiwix.org
```

Problem is the `--include` setting.

Without this setting, everything works fine.

**Comment by benoit74** [comment]
("works fine" meaning, zimit completes successfully ; I assume the ZIM does not contains what the user expected, but that's another topic)

**Comment by rgaudin** [comment]
👍  thanks
