### ISSUE TITLE
ZIM entry title should not have control characters

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#128]
Under certain circumstances, zimit/warc2zim can create "broken" ZIM entry titles, see:
https://github.com/kiwix/libkiwix/issues/1020

See the ZIM specification (which has been udpated):
https://wiki.openzim.org/w/index.php?title=ZIM_file_format&type=revision&diff=31304&oldid=31263

Warc2zim should not allow that. What to do - to avoid creating a broken ZIM file - is unclear. For the moment, removing the control-characters seems to me to be the best approach.

**Comment by benoit74** [comment]
Will be done in https://github.com/openzim/python-scraperlib/issues/159

**Comment by benoit74** [comment]
Upstream change pending review, this will be an automatic drop of control character so no change expected in warc2zim, only updating to latest scraperlib once released should be sufficient.
