### ISSUE TITLE
Correctly detect requests are coming from ajax.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/warc2zim#140]
When requests are made from ajax, wombat will rewrite the response. So we must not statically rewrite the content as it will be rewritten twice.

For now we just avoid rewriting the content for POST request but it is far from perfect (not to call it simply wrong)

We could probably have this information from browsertrix-crawler at scraping time.

**Comment by rgaudin** [comment]
Upstream: https://github.com/webrecorder/browsertrix-crawler/issues/451

**Comment by kelson42** [comment]
@benoit74 AFAIK we have seriously moved forward on this topic. This issue would the probably benefit from an update.

**Comment by benoit74** [comment]
I don't think so, as far as I've understood the issue at least ^^

Progress so far mostly only concerned "how to properly compute the ZIM paths / how to properly rewrite URLs". I did not made much changes (if any at all) regarding which content needs to be rewritten or ignored.

But I agree it should be pretty easier now to check if something needs to be done / is feasible / or not.

**Comment by benoit74** [comment]
Not clear at all what is left to be done now that we are using `WARC-Resource-Type` since 2.0.1.

Closing this issue, most of the job is done and we will open more specific issues once we encounter a real problem to solve.
