### ISSUE TITLE
Treat Wombat as a dependency

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#143]
Wombat.js should not be included in our repo. It should be downloaded from a release instead.

https://github.com/webrecorder/wombat/pull/128 tracks our patch ; if this can't make it upstream, we should patch the downloaded version.

**Comment by Jaifroid** [comment]
Presumably this is for v2.0. You're probably aware that `wombat.js` and wombat worker are included in `sw.js` as two very long minified strings. This may be irrelevant going forward as we are ditching the Service Worker, but it does bloat `sw.js` unnecessarily IMO, especially as we currently include wombat.js in every ZIM as well.

(Having said that, my implementation in the Browser Extension extracts and uses the version included in `sw.js`, so  in the unlikely event that this were to be changed, I'd need to know.)

**Comment by mgautierfr** [comment]
Last version of wombat (https://github.com/webrecorder/wombat/releases/tag/v3.7.0) contains our fix.
So we are good to use (and download) the release instead of embed it in our repo.

**Comment by kelson42** [comment]
Fixed by https://github.com/openzim/warc2zim/pull/146
