### ISSUE TITLE
Document wombat js upstream

### ISSUE THREAD

**Issue by mgautierfr** [openzim/warc2zim#145]
https://github.com/webrecorder/wombat is a nice project and our solution is totally based on it.

However, there is no documentation on how it's working or how to configure it.
It would be nice to create this documentation and send a PR to improve wombat.

**Comment by Jaifroid** [comment]
It's certainly very much needed! But do we (you) have enough info to make such a PR? See also https://github.com/webrecorder/wombat/issues/129, where it seems there is an "all or nothing" approach to documentation.

**Comment by kelson42** [comment]
@mgautierfr Can you please make an approach proposal?

**Comment by benoit74** [comment]
Making all this documentation has been judged an overwhelming / not worth it effort for now.
We already have some comments in our codebase for what looks important.
Let's close this issue until we have something really specific needed.
