### ISSUE TITLE
Clarify iframe requirement

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#15]
Displaying the content inside an iframe has a number of consequences (page title, taskbar/links, access to DOM from outside JS/CSS, etc).

We'd like to understand how much of a requirement this is and what are the reasons behind choosing this instead of a plain page for our use case.

**Comment by ikreymer** [comment]
The system uses webcomponents and iframes to run in a fully isolated environment. For example, the page does not have to worry about the top bar obscuring a part of the page, because it is fully isolated from page rendering.
While it may be ok for many pages, there are also many pages were replay without an iframe causes strange artifacts.
For example, compare the internet archive version of `https://example.com/` (which does not use iframes): http://web.archive.org/web/20200727054239/https://example.com/ with the live https://example.com/
An iframe prevents this type of issues

Are there specific issues that you are concerned about? If so, it may be possible to address them. for example, the page title could easily be set, along with favicon from the initial page. The embedded mode also provides its own wrapping, as it is designed to even support multiple replays in a single page, but they could be addressed if there is a specific issue.

**Comment by rgaudin** [comment]
OK, so the sole reason in favor of iframe would be to ensure the rendering is OK as it is isolated? I'd prefer we're clear on the reasons so that if someone comes up with a solution for this point, we don't have to redo this whole discussion again.

As for the requirements, here's what's on my mind at the moment:
- Page title
- Page favicon
- external links blocker (https://github.com/kiwix/kiwix-lib/blob/master/static/skin/block_external.js)

**Comment by ikreymer** [comment]
Yep, this can all be supported. I think the service worker would intercept all navigation events to external pages, not just `<a>` links.

**Comment by rgaudin** [comment]
> Yep, this can all be supported. I think the service worker would intercept all navigation events to external pages, not just `<a>` links.

Well we don't want the SW to intercept it but we want to be able to catch it in kiwix serve using the linked script to change the behavior (redirect in this case).

Will this continue to work ? (you can test with appropriate param on kiwix-serve) Does the JS script need to be adapted?

**Comment by ikreymer** [comment]
> > Yep, this can all be supported. I think the service worker would intercept all navigation events to external pages, not just `<a>` links.
> 
> Well we don't want the SW to intercept it but we want to be able to catch it in kiwix serve using the linked script to change the behavior (redirect in this case).
> 
> Will this continue to work ? (you can test with appropriate param on kiwix-serve) Does the JS script need to be adapted?

No, that script won't work with the current service worker based replay (and is designed to filter out all urls the start with https://, but the replay handles that). The script just redirects to something like this:
https://dev.webrecorder.net:9003/catch/external?source=https://example.com/

But the service worker viewer can render this same exact page too so there is no difference in behavior

**Comment by rgaudin** [comment]
How would you know when to trigger that ? It's triggered in kiwix serve only if the flag is set.

Also it would mean maintaining the same feature twice...

We're also using that redirect link on proxy servers to rebrand it but that won't be affected I believe

**Comment by ikreymer** [comment]
> How would you know when to trigger that ? It's triggered in kiwix serve only if the flag is set.

Hm, is this something that could be exposed as an api, if the flag is set or not? Are the options: automatically redirect to external page or show warning first? How does it work on desktop/android/ios?

**Comment by rgaudin** [comment]
This feature is only used in kiwix-serve AFAIK because it's app-less so there's no alternative.

Readers do as they please ; I know that iOS triggers a dialog asking what to do (Cancel/Load the link)
![IMG_FBA143DA18B5-1](https://user-images.githubusercontent.com/57929/89161274-ad609f00-d572-11ea-9c7f-e36890431ce9.jpeg)

**Comment by ikreymer** [comment]
In the new setup, the system will attempt a redirect to the live web for URLs outside the current domain.

A way to look at it is the replay is in a sandbox. When the sandbox encounters a 404, it can do several things:
- Show a 404
- Redirect to live web directly
- Redirect to the warning page, which has a link to live web.

The most generic solution is to load the specified 404 page, `A/notFoundPage.dat` (.dat now to avoid being stored as text/html in the zim)

The template can then handle what to do.

I think all of the concerns with the iframe have now been addressed: title, favicon, and live redirect should be working as expected.

**Comment by rgaudin** [comment]
OK, I think all the iframe-related issues we've had so far have been fixed.
