### ISSUE TITLE
Adopt python bootstrap standards

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#152]

**Comment by kelson42** [comment]
@benoit74 Is that somehow blocking or strongly impacting Zimit2?

**Comment by rgaudin** [comment]
That's what we discussed during the initial zimit2 PR. We agreed we'd do it right after @mgautierfr finishes so I guess that's why @benoit74 included it.
It's not a big effort and @benoit74 already switched zimit (smaller though) so I'd advise we keep it but it's not required.

**Comment by kelson42** [comment]
@rgaudin Thx, make sense. Was kind of focused on Milestone 1 by @mgautierfr and have forgotten Milestone 2 handled by @benoit74... but at the end it seems we want to handle everything with the same Github project.

**Comment by benoit74** [comment]
PR for warc2zim is almost ready indeed ; while it is not a blocker, it might impact Zimit2 in the sense that it will be a significant list of small subtle changes in the codebase and as such I would prefer to do it while we have a lot of attention on warc2zim / zimit

**Comment by kelson42** [comment]
@benoit74 I think this has been fixed by #154  right?

**Comment by rgaudin** [comment]
Right
