### ISSUE TITLE
Should we inject the kiwix-serve taskbar on articles?

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#16]
https://github.com/openzim/warc2zim/pullsAt the moment, we are injecting (or not preventing injection of) the taskbar in the player and blocking it for the other articles such that we don't end-up with two taskbar.

How feasible would it be to do the opposite?

* Block it on player only
* Leave it be injected on every (HTML) article

I think I have part of my answer in the *HTML* part so that leaves me to #17

**Comment by ikreymer** [comment]
Doing it differently would cause a lot of issues. The replay system assumes that everything on the page is part of the page, so would need special handling for the `/skin/...` urls that are injected, and there is no way to know that these are from kiwix and not from a site, eg.`https://example.com/skin/jquery-ui/jquery-ui.min.js`.

Then, there is still issue of other iframes, a site may have other iframes (for example, video embeds) that also include html. Would need some way to indicate that this html is not top-level, and not inject it there. Of course, libkiwix would not know what is an iframe and what isn't until it is loaded in the browser.

I think whis would lead to many complications and result in worse replay than what we have now.

**Comment by rgaudin** [comment]
Thank you I understand those two points can't easily be fixed otherwise.

It's important to note that this has the incidence of putting all HTML articles on a different mimetype than `text/html` (to prevent the taskbar) which itself has for consequence (will have, shortly) to remove those articles out of the Random feature.
