### ISSUE TITLE
Zimit2: Should we rewrite JSON?

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#160]
See https://github.com/openzim/warc2zim/pull/158#discussion_r1467769011 for details

**Comment by rgaudin** [comment]
I believe wabac rewrites JSONP and not JSON. I suppose it rewrites the callback as JS.

**Comment by kelson42** [comment]
Do we need this to have a succesfull Zimit 2.0 version?

**Comment by Jaifroid** [comment]
See the use case in #181 which suggests yes, we should rewrite JSON for a successful zimit2, depending on how we define "successful" (e.g. parity of features with zimit1?). In that case, the compatibility tables are one of the most useful features of MDN from a Web developer's perspective (and developers are the target audience of MDN).

**Comment by kelson42** [comment]
Fixed by https://github.com/openzim/warc2zim/pull/192
