### ISSUE TITLE
[Query] About encoding of URLs and query strings in zimit2

### ISSUE THREAD

**Issue by Jaifroid** [openzim/warc2zim#164]
Partly prompted by @mgautierfr's comment below and the work I've been doing adapting KJS to recognize zimit2 archives in certain special cases: I need to know whether URLs in zimit2 ZIMs are stored with URI encoding, and whether the querystring is significant and needs to be parsed (as is the case with zimit classic).

The reason I ask is that zimit classic stores all URLs with URI encoding (as produced by `encodeURI`, or `encodeURIComponent` minus forward slashes), and I have code to deal with this when reading zimit classic archives. It includes encoding of the querystring. However, the openZIM spec [explicitly forbids storing encoded URIs](https://openzim.org/wiki/ZIM_file_format#URLs), and so a conforming reader (as KJS was) has to work around this.

Basically, do I need to `decodeURI` systematically on all zimit2 URLs in the cases where I have to process them? Mostly I don't have to process them, but there are a few cases, including detection of content that needs to be loaded outside of the sandbox, title search, and also displaying zimit2 content in old browsers that only support our jQuery mode.

Regarding the querystring, if I've understood the implications of @mgautierfr's comment correctly, this is removed in the Python code that rewrites URIs? Is this always the case for ZIM URLs? (I realize the case commented on was to do with non-ZIM, or external URLs.)

> It is normal and wanted that we encode `?`. This "query string separator" for wordpress is not one for kiwix. We don't want the kiwix server to discard it (well, here, we may, but in general not)
> 
> I would say that the problem is that we remove the query string when we check if the url point to an existing entry.
> 
> But anyway, even when not removing the querystring during rewrite. The url is actually detected as not in the zim, so not rewritten (`https://mesquartierschinois.wordpress.com/2014/07/18/carme/?share=twitter)`. But at runtime, wordpress js is rewritting the url (with a `&nb=1` prepend), so wombat is catching this rewrite and transform it.
> Keeping external link is working at creation time, all url are rewritten by wombat.
> 
> _Originally posted by @mgautierfr in https://github.com/openzim/warc2zim/issues/163#issuecomment-1914284279_
>

**Comment by mgautierfr** [comment]
I will try to answer all your questions in my own way 🙂 :

Let's say we have a website which has a endpoint `/foo` which generate a data based on the querystring. And an article with a url `/foo?name=bar`.
zimit scrapper will visit `/foo?name=bar` and put a record with this url in the warc. As long as there is not link to `/foo` we will have no entry `/foo`.

On warc2zim, we loop on the records of the warc and create entry with a normalized url in the zim file. So we will store the entry using the path `foo?name=bar`.
We we rewrite the content (either statically or dynamically in wombat), we rewrite the url `/foo?name=bar` to `/foo%3Fname%3Dbar`. So we we send the request, the server doesn't try to interpret the querystring. It decode it to `/foo?name=bar` and search for the entry `foo?name=bar` in the zim file (and found it).

In fact, there is two steps, and you have to respect them:
- Parsing the request : handle query string (if any), remove it, urldecoded what lefts.
- Search for entry in zim using what left (urldecoded) from previous step.

So, in ALL case (except when you try to replace wabac/sw in zimit1), you should ignore the query string (at least kiwix-serve does). Then urldecode the url, and search for the decode string in the zim file (and don't care if there is a `?` in it)

**Comment by Jaifroid** [comment]
Thank you, @mgautierfr, it's very helpful. Some of the details are a bit different for the KJS backend, as we have to send it the URL in the exact same format in which it is stored (unencoded, it seems, for zimit2, encoded for zimit1), as we don't benefit from the server's translation of encoded URIs that standard httpd servers do.

I'd like to keep this issue open until I've finished testing, in case of any further clarifications.

**Comment by Jaifroid** [comment]
Just documenting some empirical examples that support what is written above.

All the examples of percent-encoding of URLs that I have found so far appear to be in querystrings:

![image](https://github.com/openzim/warc2zim/assets/4304337/ef6d7a03-0355-46e0-ba9c-bd07f2b5a224)

**Comment by Jaifroid** [comment]
Closing, will reopen if any issues.
