### ISSUE TITLE
Setup a test website with all weird JS situations

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#166]
See https://github.com/openzim/warc2zim/issues/165#issuecomment-1918546746

We need to setup a test website (and associated Zimfarm recipe) grouping all "weird" JS situations that are fixed by wabac DS rules at `src/warc2zim/content_rewriting/ds.py`, so that it will be quick to test all of them at once.

**Comment by kelson42** [comment]
@benoit74 Yes, this can be easily done with https://pages.github.com/

**Comment by benoit74** [comment]
I'm not concerned about the technical side (we could also setup a small website on our own infra, but you are right Github Pages is maybe even more straightforward).

I'm more concerned about ensuring we have the proper content inside the test website so that we test all weird situations, and we need expertise on that.

**Comment by kelson42** [comment]
Fixed by https://github.com/openzim/warc2zim/pull/184
