### ISSUE TITLE
[zimit2 query] Will production ZIMs have minified and babelified version of wombat.js (and wombatWorkers.js)?

### ISSUE THREAD

**Issue by Jaifroid** [openzim/warc2zim#171]
I know back in May at the hackathon I asked for a non-minified version of wombat.js to work with. It seems that the version of wombat in the test ZIMs is unminified (see screenshot) and (maybe?) has not been processed by Babel. In any case, it is not compatible with some older browsers or frameworks.

I've run into this issue in preparing the UWP app for release, as wombat throws several errors in that old framework. That's probably a hopeless case, and I'll just have to work around what I can, as I doubt even Babel could make it fully compatible with Edge 18 given its complexity.

But this raises the broader issue of whether we intend to minify and target wombat / wombatWorkers for, say, the last few browser editions of Chrome, Firefox and Safari at least in production ZIMs?

![image](https://github.com/openzim/warc2zim/assets/4304337/a250190a-2042-4b46-883d-2ed6231f40ac)

**Comment by mgautierfr** [comment]
We are downloading `wombat.js` (and in near future `wombatWorkers.js`) from https://cdn.jsdelivr.net/npm/@webrecorder/wombat@3.7.0/dist/
They are already minified.

In early version of warc2zim2, we were using an embedded (patched) version of wombat. This is probably why you have unminified wombat.

**Comment by Jaifroid** [comment]
OK, great, thank you!
