### ISSUE TITLE
Incompatible regexp in fuzzy substitutions in `wombat_setup.js` blocks video in iOS Safari (at least)

### ISSUE THREAD

**Issue by Jaifroid** [openzim/warc2zim#174]
As part of #144, I tested the "orca" video in 100rabbits (26th Jan version) on iOS Safari (using the PWA, via Browser Stack live testing). There is a blocker on this platform due to an incompatible regular expression. It seems the "googlevideo" regex (see highlighted line in screenshot) uses a syntax that is not supported in Safari, and stalls with the error "Invalid group specifier name". I didn't test Firefox or Chrome on iOS, but all browsers currently have to use the Safari engine on iOS. This might or might not affect the web view in the official app, but preliminary reports suggest it's not working there either.

I think this issue somehow is tangentially related to #171, because Babel can take care of ensuring cross-browser compatible syntax is used or polyfilled if necessary.

![image](https://github.com/openzim/warc2zim/assets/4304337/f03e0c9e-45fe-48bd-b542-7ab7f05983dd)

Ping @mgautierfr

**Comment by Jaifroid** [comment]
The issue seems to be due to the use of lookbehind assertions `(?<=...)`. See https://caniuse.com/?search=Lookbehind. On iOS 16.3 and below, these are incompatible with Safari. The good news is that it would work on latest iOS in principle, but probably not the webview unless very recently updated.

**Comment by kelson42** [comment]
Fixed by https://github.com/openzim/warc2zim/pull/204
