### ISSUE TITLE
Investigate js vs module rewrite.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/warc2zim#189]
This issue tries to resume our problem about rewrite js as module or classic script.
For information, a document about module can be found at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules

## What is different in our rewriting

In our case, with the PR #172, we rewrite `*.module.js` file differently that other `*.js` file.
When using both transformation on `*.module.js` related to vimeo we have the following differences:

### Script header

At beginning of script/module we insert some js code to mock the classical structures the script may use.

For classic js, it is:
```js
var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
let window = _____WB$wombat$assign$function_____("window");
let globalThis = _____WB$wombat$assign$function_____("globalThis");
let self = _____WB$wombat$assign$function_____("self");
let document = _____WB$wombat$assign$function_____("document");
let location = _____WB$wombat$assign$function_____("location");
let top = _____WB$wombat$assign$function_____("top");
let parent = _____WB$wombat$assign$function_____("parent");
let frames = _____WB$wombat$assign$function_____("frames");
let opener = _____WB$wombat$assign$function_____("opener");
let arguments;
```

For module it is:
```js
import { window, globalThis, self, document, location, top, parent, frames, opener } from "../../../../_zim_static/__wb_module_decl.js";
```

The content of `__wb_module_decl.js` can be found in https://github.com/openzim/warc2zim/blob/warc2zim2/src/warc2zim/statics/__wb_module_decl.js

This is because of https://github.com/openzim/warc2zim/blob/warc2zim2/src/warc2zim/content_rewriting/js.py#L265-L266

### Inner transformation.

`import` function call are rewritten differently, a `import(foo)` will be rewritten:
- for classic js : `____wb_rewrite_import__("", t.href)`
- for module : `____wb_rewrite_import__(import.meta.url, t.href)`

This is because of https://github.com/openzim/warc2zim/blob/warc2zim2/src/warc2zim/content_rewriting/js.py#L99-L112

## How we detect it is a module

When script is imported from html, the `type="module"` attribute mark the script as being a module:
`<script type="module" src="main.js"></script>` or `<script type="module">...</script>`.
Else it is a module.

If script is also imported with a `import` (in a module only ?), it must also be used as a module.

In #172, we check the `type="module"` for inline script and if `module.js` is present in the path for item.
We also use some regex on the content to detect if it is a module: https://github.com/openzim/warc2zim/blob/warc2zim2/src/warc2zim/content_rewriting/js.py#L239-L244, but it was there before #172, so either is not enough or it is buggy.

**Comment by Jaifroid** [comment]
Can you clarify if this only affects Vimeo for now? Do you have other scenarios where it's not working?

**Comment by benoit74** [comment]
While we were expecting https://github.com/webrecorder/browsertrix-crawler/issues/451 to provide all needed contextual informationto differentiate a module from classic JS, it is now clear that the information is not even known by the rendering engine itself. The rendering engine only knows he is loading a script, but not how the JS engine intend to use it. The JS engine will probably not expose this information easily.

For now, we are hence back to the original proposition discussed some time ago (but not traced back in this issue): rewrite the JS files two times (and only the files), once supposing it is classic JS, once supposing it is module JS. And use the proper version when we encounter a `<script type="module" src="..."></script>`. Inline JS is already rewritten properly, we already take into account the fact that it is a module or classic JS.

**Comment by benoit74** [comment]
Having almost implemented a first version of the code, I begin to doubt this is the proper solution. Looks quite dirty/clunky in fact. The clunky side of this first solution appears once you realize that you have to compute a new (second) ZIM path for a given item. Modifying the url path seems risky/complex, so I decided to "simply" add a "magic" query parameter. But they you realize that this new query parameter interfer with some fuzzy rules, e.g. the one which says that if there is only digits in the query part, it must be removed ... and there is not only digits left ... and they are not removed ... And this is the simple example, we might run into other weird interactions with the fuzzy rules. Another alternative would be to add the query string after the processing of fuzzy rules but this is even more complex from what I see.

I will investigate as well the other solution which would be to properly process the whole tree of JS dependencies to detect what is a script and what is a module. Looks like we have a well developed Python parser for JS: https://pypi.org/project/esprima/ ; not a lot of activity, but seems to cover the whole codebase ; I will probably have a look at how it behaves on the test website JS. I should probably add few more test cases to this test website for better coverage of the JS part, but I will already see how it behaves with Vimeo.

**Comment by mgautierfr** [comment]
> Modifying the url path seems risky/complex, so I decided to "simply" add a "magic" query parameter. But they you realize that this new query parameter interfer with some fuzzy rules, e.g. the one which says that if there is only digits in the query part, it must be removed ... and there is not only digits left ... and they are not removed ... And this is the simple example, we might run into other weird interactions with the fuzzy rules. Another alternative would be to add the query string after the processing of fuzzy rules but this is even more complex from what I see.

Adding a prefix seems less error prone:
`<moduleprefix>/exemple.org/path?query` vs `exemple.org/path?query`

This should not interfere with specific site url (especially if it contains the "marker") and regex transformation should be minimal (it could even add a small wrapper removing/readding it before/after fuzzy rules application)

**Comment by benoit74** [comment]
I've finally done it the other way, I'm rewriting the JS only once by detecting properly whether the file is used as a module or as classic JS. It is quite straightforward in fact, PR will be ready by the end of the week hopefully.
