### ISSUE TITLE
Do not include `resource` WARC records inside the ZIM

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#197]
https://github.com/webrecorder/browsertrix-crawler/issues/457 and https://github.com/webrecorder/browsertrix-crawler/pull/458 have introduced more systematic use of `resource` WARC records.

As of 1.0.0-beta5, `resource` WARC records are used for:
- thumbnails
- screenshots
- text extracts
- page infos (mentioned above)

All these resources while potentially useful for warc2zim logic (especially the page infos, we do not use thumbnails, screenshots and text extracts for now) should not be directly embedded inside the ZIM, at least not as a response record is.

**Comment by kelson42** [comment]
Fixes by https://github.com/openzim/warc2zim/pull/198
