### ISSUE TITLE
Should we remove the favicon download fallback

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#202]
When a favicon URL is passed at the CLI, the scraper downloads this favicon and use it as ZIM illustration.

When no favicon URL is passed at the CLI, the scraper uses the favicon he finds on the main page as ZIM illustration.

In this second case, the favicon is first searched for in WARC records.

While this favicon should be present in WARC records (and usually is), there is also a fallback to download it from the web.

@rgaudin @mgautierfr) consider that this fallback download makes no sense and should be removed (see https://github.com/openzim/warc2zim/pull/196#issuecomment-1973306252 and https://github.com/openzim/warc2zim/pull/196#issuecomment-1973567648).

I do not agree, I find it weird to allow to download the favicon with the "CLI" favicon URL but not from the "guessed" favicon URL.

It will lead to a situation where the ZIM is either not produced (if we fail the scrape when "guessed" favicon is missing from the WARC) or produced with wrong illustration (if we use default PNG when "guessed" favicon is missing from the WARC), and we finally have to set the guessed favicon URL at CLI and restart the scraper to have the proper ZIM illustration. The scraper is better like today where he tries to intelligently solve issues without manual intervention.

**Comment by rgaudin** [comment]
Favicon is a resource (in browsertrix's terms) so it's not affected by scope. What scenario would have it not be present in WARC but us able to parse and download  it correctly?

**Comment by benoit74** [comment]
> Favicon is a resource (in browsertrix's terms) so it's not affected by scope. What scenario would have it not be present in WARC but us able to parse and download it correctly?

Probably none, you're right

**Comment by benoit74** [comment]
I.e. we should not fallback to download what is already present in the WARC or not available at all. And use the default PNG in such a situation.

**Comment by benoit74** [comment]
Closed by https://github.com/openzim/warc2zim/pull/196
