### ISSUE TITLE
Zimcheck does not pass with bouquineux.zim

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#21]
```
$zimcheck  bouquineux.zim 
[INFO] Checking zim file bouquineux.zim
[INFO] Verifying Internal Checksum.. 
  [INFO] Internal checksum found correct
[INFO] Searching for metadata entries..
[INFO] Searching for Favicon..
[INFO] Searching for main page..
[INFO] Verifying Articles' content.. 
[INFO] Searching for redundant articles..
  Verifying Similar Articles for redundancies..
[ERROR] Missing metadata entries :
  Entry A/www.bouquineux.com/pdf/Tchekhov-La_Steppe.pdf is empty
  Entry A/www.bouquineux.com/pdf/Tchekhov-Trois_ans.pdf is empty
  Entry A/www.bouquineux.com/pdf/Tolstoi-Contes_et_nouvelles_-_Tome_III.pdf is empty
[ERROR] Missing metadata entries :
  Title
  Creator
  Publisher
  Description
[ERROR] Missing favicon :
_Map_base::at
```

**Comment by kelson42** [comment]
I guess #4 already handles the lack of metadata/favicon... but the missing PDF seems to be an other problem.

**Comment by rgaudin** [comment]
There are three problems listed here:

* Articles without data (see #23)
* Missing metadata (see #1 and #4)
* Missing favicon entry at `-/favicon` (see #4)

@ikreymer, if you don't have it, you can get zimcheck in the [zim-tools](http://download.openzim.org/release/zim-tools/).

**Comment by ikreymer** [comment]
These files are empty from the site:
http://www.bouquineux.com/pdf/Tolstoi-Contes_et_nouvelles_-_Tome_III.pdf
http://www.bouquineux.com/pdf/Tchekhov-Trois_ans.pdf
http://www.bouquineux.com/pdf/Tchekhov-La_Steppe.pdf

I don't think empty responses should be considered errors, this is what the site offers.
If they are excluded, then it will just be a 404/not found, which seems less correct for the user..

**Comment by ikreymer** [comment]
A solution to fix validation would be to write the `H/...` record but not the `A/...` record, and if the headers indicate that the payload is 0 length, don't attempt to load it at all.

**Comment by ikreymer** [comment]
After removing the empty entries, `zimcheck` still seems to be confused by some URLs that are actually in the ZIM.
Perhaps a different checking mode is needed? Note that URLs starting with `http://` or `https://` are not necessarily external -- it depends on the domain, since ZIMs created from WARCs can have data from multiple domains, if necessary.

**Comment by kelson42** [comment]
Seems to work fine now :)

**Comment by ikreymer** [comment]
Ah ok! hm, i was still seeing some strange errors with the 2.0.0. version from: https://download.openzim.org/release/zim-tools/ but maybe that's not the latest..
