### ISSUE TITLE
Links to server root are not working

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#210]
See https://dev.library.kiwix.org/viewer#www.solidarite-numerique.fr_fr_all_2024-03/www.solidarite-numerique.fr/

The link on big button "Accueil" has not been rewritten, probably considered out of the archive because it miss the trailing "/". TbC.

![image](https://github.com/openzim/warc2zim/assets/7102089/5d94d791-bff0-472e-ad42-a5aaf2438d21)

**Comment by benoit74** [comment]
This is intentional, we even have a test for it:

```
        assert normalize("https://exemple.com") == "exemple.com"
        assert normalize("https://exemple.com/") == "exemple.com/"
```

However, I don't think this is a good idea, since not in accordance with RFC3986 as far as I've understood. Section 6.2.3 is really clear on this: https://www.rfc-editor.org/rfc/rfc3986#section-6.2.3

I think we should ensure that following tests passes (I chose to normalize to a value without trailing slash, but we can choose the trailing slash, I do not have any argument for now):

```
        assert normalize("https://exemple.com") == "exemple.com"
        assert normalize("https://exemple.com:") == "exemple.com"
        assert normalize("https://exemple.com:/") == "exemple.com"
        assert normalize("https://exemple.com:80/") == "exemple.com"
        assert normalize("https://exemple.com/") == "exemple.com"
```

**Comment by rgaudin** [comment]
> I think we should ensure that following tests passes (I chose to normalize to a value without trailing slash, but we can choose the trailing slash, I do not have any argument for now):

`exemple.com` is not valid and is converted to `exemple.com/` by most (all) tools/readers. I'd probably chose the trailing slash version for that reason

**Comment by benoit74** [comment]
> exemple.com is not valid

You mean in HTTP standard, correct? I think it is valid from a URI perspective, but not from the HTTP standard.

E.g. https://www.rfc-editor.org/rfc/rfc2616#section-5.1.2 states that:

```
   [...] Note that the absolute path
   cannot be empty; if none is present in the original URI, it MUST be
   given as "/" (the server root).
```

**Comment by Jaifroid** [comment]
For our purposes, we want the matching regular expression to be as broad as possible. I don't know exactly how it matches, but we want requests to `http://www.example.com` to be understood to be in the ZIM, as well as requests to `http://www.example.com/`.

I actually had to work around this in Kiwix JS when checking what a user clicks on for zimit2 ZIMs I had to use this bit of code:

```
// If URL has final slash, we need to try it without the slash
if (/\/$/.test(zimUrl)) {
    zimUrl = zimUrl.replace(/\/$/, '');
    return appstate.selectedArchive.getDirEntryByPath(zimUrl).then(function (dirEntry) {
        if (dirEntry) {
            processDirEntry(dirEntry);
        } else {
            // If dirEntry was still not-found, it's probably an external link, so warn user before opening a new tab/window
            uiUtil.warnAndOpenExternalLinkInNewTab(null, anchor);
        }
    });
}
```
This code is part of a longer routine that checks whether a URL is in the ZIM, and if not, offers to open it in an external tab or window. I am forced to do this checking, because otherwise the resource gets blocked by the sandbox and/or by CORS rules, and the app ends up in an unusable state.

**Comment by benoit74** [comment]
@Jaifroid the issue you mentioned should probably not be fixed reader side (otherwise all reader will have to do it, this is going to be a nightmare to manage) but scraper side. The scraper is already rewriting all links, it just produced an invalid HTML/ZIM here. This should have been reported here before any implementation reader-side. At least I've done the necessary so that nothing needs to be done reader-side and it will come soon in a PR.

**Comment by benoit74** [comment]
Solved by https://github.com/openzim/warc2zim/pull/218
