### ISSUE TITLE
Zimit2: Document what is known (or supposed) to work and known limitations (or not tested at least)

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#214]
It is becoming more and more important to document what is known to work and what is not to not be supported (yet or at all).

I propose a first list, @mgautierfr your help is welcomed on this

What is supported:
- ??? (I struggle to have a clear wording of what is currently supported)

What is not yet supported (but should be soon as part of Zimit2):
- pages and resources whose URLs have characters which should be encoded to be a valid URL according to W3C specification
- pages and resources whose URLs have a querystring: the querystring is more or less ignored for now, it might work if the querystring is not important (since it is usually dropped by the reader)
- pages and resources on domain name with characters which should be punny-encoded: if the 
- Javascript code doing string manipulation to compute URLs: these URLs are not rewritten and there is a significant chance they won't work
- Javascript modules: only partial support for now

What is not supported:
- mix of HTTP and HTTPS with two different resources at same hostname and path: scraper takes the simplification this situation does not exist, and does not take into account the protocol when computing ZIM entry path. E.g. if http://www.acme.com/resource1 and https://www.acme.com/resource1 both exist AND lead to different resources, the scraper will fail
- replay of HTTP response headers: these headers are not stored inside the ZIM / not replayed
- HTTP request headers: if two different request header values leads to two different page / resource, scraper is ignoring this information
- User-Agent: corollary of the point above on HTTP request headers, scraper supposes a single User-Agent has been used to create the WARC files ; if the website is providing different content based on the User-Agent, only one will be used

What I don't know at all:
- HTTP/2: ?

**Comment by benoit74** [comment]
Not supported:
- mix of multiple ports with two different resources at same hostname and path: scraper takes the simplification this situation does not exist, and does not take into account the port number when computing ZIM entry path. E.g. if `http://www.acme.com:80/resource1` and `http://www.acme.com:8080/resource1` both exist AND lead to different resources, the scraper will fail

**Comment by mgautierfr** [comment]
What is supported:
- Basic static website (html/css)
- Partiall support for POST request (at best, do as it has been recorded)
- Basic js (doing no request)
- Js doing basic fetch request to get data

What is not supported:
- Any web site expecting a server to store its data and wanting to modifying those data
  (form, read/write api, ...)
- ~~Javascript code doing string manipulation to compute URLs: these URLs are not rewritten and there is a significant chance they won't work~~ This is supposed to work as wombat is catching all request and rewrite the url.

What I don't know at all:
- HTTP/2: Probably out of scope (but supported), http/2 should be transparent for us.

**Comment by kelson42** [comment]
I think this is really important as well to document the overall architecture and articulation with Browsertrix/web.replay. In particular all the stuff around fuzzy rules, URL rewriting which is inherited from there.

**Comment by benoit74** [comment]
Fixed by https://github.com/openzim/warc2zim/pull/269
