### ISSUE TITLE
Add new upstream wabac.js fuzzy rules and keep track of sync commit

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#216]
The scraper has fuzzy rules coming from wabac.js fuzzy matcher: https://github.com/webrecorder/wabac.js/blob/main/src/fuzzymatcher.js

These rules have been updated at the source but changes have not been back-ported.

One significant thing I noticed is that some rules (e.g. https://github.com/webrecorder/wabac.js/blob/c1124c0d93e44ff0005d4df960d989c6e7295534/src/fuzzymatcher.js#L57-L65) are returning multiple URLs while we do not take this into account. This is particularly visible in the tests: https://github.com/webrecorder/wabac.js/blob/c1124c0d93e44ff0005d4df960d989c6e7295534/test/fuzzyURL.js#L26-L30.

Is it something intentional? @rgaudin @mgautierfr any memories to share around this?

Another significant change is that more websites (washingpost, twitter, ...) are now supported by Wabac.js in this file.

This is an issue for both zimit1 and zimit2, but I suggest to fix this only for zimit2. WDYT?

**Comment by kelson42** [comment]
What would be very great is to find a system to have a strong relationship between our version of the rules and the one upstream in wabac.js so the whole stuff is easier to track.

**Comment by rgaudin** [comment]
Current approach seems to have been to _adapt_ the fuzzyrules to replicate the feature. Probably easier to maintain if the upstream updates are low.

```js
{
    "match": /\/\/.*googlevideo.com\/(videoplayback)/i,
    "fuzzyCanonReplace": "//youtube.fuzzy.replayweb.page/$1",
    "args": [
      ["id", "itag"],
      ["id"]
    ],
    "fuzzyArgs": true
}
```

```py
{
    "pattern": r".*googlevideo.com/(videoplayback(?=\?)).*[?&](id=[^&]+).*",
    "replace": r"youtube.fuzzy.replayweb.page/\1?\2",
}
```

If those are frequent, it might make sense to ask them to move the rules themselves into a dedicated JSON and reimplement a similar `FuzzyMatcher` that parses and transforms the rules. That piece of code would still need to be monitored/updated though.

Given the list of rules is limited, I think our current approach is the cheapest for now. There hasn't been any update in 3m so maybe we keep this until changes become too frequent?

**Comment by rgaudin** [comment]
@benoit74 regarding zimit1, given wabac.js is bundled, it's just a matter of updating it.

**Comment by benoit74** [comment]
> What would be very great is to find a system to have a strong relationship between our version of the rules and the one upstream in wabac.js so the whole stuff is easier to track.

This is already in place in warc2zim2 for ds-rules: see first line comments of https://github.com/openzim/warc2zim/blob/warc2zim2/src/warc2zim/content_rewriting/ds.py

The same needs to be done for fuzzy rules.

> @benoit74 regarding zimit1, given wabac.js is bundled, it's just a matter of updating it.

Then why are these rules inside the Python codebase as well? I think zimit1 also needs it.

> Current approach seems to have been to adapt the fuzzyrules to replicate the feature. Probably easier to maintain if the upstream updates are low.

True, but I think we need still need to generate two ZIM entries (or more exactly a ZIM entry and an alias) in the case you mention, to have access to both URLs, one with only the `id` param, and one with `id` and `itag` param. I don't get yet how this could work in practice (which URL should we use when rewriting HTML/JS code typically?)

**Comment by rgaudin** [comment]
> Then why are these rules inside the Python codebase as well? I think zimit1 also needs it.

Right! Reminds me we never updated those (although we did update wabac.js)

**Comment by benoit74** [comment]
> Right! Reminds me we never updated those (although we did update wabac.js)

Hence the fact that I mention we might want to do this change in zimit1 as well, even if I suggest this would be a waste of time.

**Comment by mgautierfr** [comment]
> Is it something intentional? @rgaudin @mgautierfr any memories to share around this?

Yes. We don't do the same things so we don't need to generate multiple url.

The fuzzymatching made by wabac is to match a requested url to an entry url, where the urls are not identical but some information (querystring value) are important to identify what have to be matched.
However, the wabac code is generic and must works with warc generated at different time, so the fuzzy matching have to check different way to match things (as url of website may have changed over time).

But us, we don't try to match things. We generate reduced url from "complex" url. And we have only one way to generate that. And once we have generate (and stored) the reduced url, we simply have to generate the same reduced url at runtime.

And as we use the same rules by definition (we generate the rules used at runtime from the rules used at creation time), we don't have to try several urls. Either we have it, either we will not find it.

**Comment by benoit74** [comment]
Great, that's a good news and it makes totally sense, we are lucky to have something in sync between the archive content and the rules which are executed.

Then the only topic left on this issue is to document this somewhere + to update the rules with new ones which appeared in wabac.js + to apply the same approach than for ds_rules to keep track of which commit was last synced.
