### ISSUE TITLE
External link to Wikipedia in Bouquineux seems broken

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#22]
Loading `bouquineux.zim` in a local kiwix-serve I open the following page:
http://localhost:8080/bouquineux/A/viewer.html#url=http%3A%2F%2Fwww.bouquineux.com%2F%3Febooks%3D346%26N%25C3%25A9mirovsky&ts=20200727182643

On that page there is a link to Wikipedi article:
http://localhost:8080/bouquineux/A/wabac/id-3d79eb55abd2/20200727182643mp_/http://fr.wikipedia.org/wiki/Ir%C3%A8ne_N%C3%A9mirovsky

This URL returns a HTTP 404:
```
$ curl -I http://localhost:8080/bouquineux/A/wabac/id-3d79eb55abd2/20200727182643mp_/http://fr.wikipedia.org/wiki/Ir%C3%A8ne_N%C3%A9mirovsky
HTTP/1.1 404 Not Found
Connection: Keep-Alive
Content-Length: 2344
Cache-Control: no-cache, no-store, must-revalidate
Access-Control-Allow-Origin: *
Content-Type: text/html
Date: Tue, 28 Jul 2020 09:20:32 GMT

```

and it should route to the online Wikipedia article https://fr.wikipedia.org/wiki/Ir%C3%A8ne_N%C3%A9mirovsky like the original page.

Remark: I believe we would really benefit here to keep the original link, ie. `https://fr.wikipedia.org/wiki/Ir%C3%A8ne_N%C3%A9mirovsky` in place of `/A/wabac/id-3d79eb55abd2/20200727182643mp_/http://fr.wikipedia.org/wiki/Ir%C3%A8ne_N%C3%A9mirovsky`

**Comment by rgaudin** [comment]
Might be related to #23

**Comment by ikreymer** [comment]
Yes, I just found the `/catch/external` that shows the warning page , I think that can easily be supported. Assume that is what would be desired here?

**Comment by kelson42** [comment]
@ikreymer Not really I believe, what is the best is just keeping the link like it was.

**Comment by rgaudin** [comment]
> Yes, I just found the `/catch/external` that shows the warning page , I think that can easily be supported. Assume that is what would be desired here?

No we want external links to stay as is ; unless blocked by kiwix-serve (optional)
