### ISSUE TITLE
Zimit2: bundle/test/release javascript getWombatInfo configuration as a real dependency

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#227]
As of today, configuration of wombat.js in warc2zim2 is done in the https://github.com/openzim/warc2zim/blob/warc2zim2/src/warc2zim/templates/wombat_setup.js file

This file is responsible to setup wombat:
- configure some constant settings (is_framed, is_live, static_prefix, target_frame, ...)
- but also configure the URL rewrite function which is responsible to transform URL captured by wombat into a URL which will be able to be served from the ZIM

As of today, this URL rewrite function is also implemented inside this same file. 

This function is very important since it is the central piece allowing wombat to redirect every JS network call to the proper ZIM resource.

The main limitation of current approach is that it is not possible to test this function easily. No tests are present as of today.

Not testing this function with a set of automated tests is a big concern from my PoV.

Should we consider to bundle/test/release this URL rewrite function as a real JS library (even if quite tiny) so that it will be more isolated and easier to test?

@mgautierfr @kelson42 @rgaudin any PoV?

**Comment by mgautierfr** [comment]
The rewrite_url function is not existing in itself. It is generated from the `FUZZY_RULES` in python.

We may indeed generate the function once and store the generated function in a separated file to be able to test it. But then we would have to remember that this is a generated function and we must regenerate it when we update `FUZZY_RULES`.
(BTW, originally, the function was stored in git, but it has been asked to me to not store it and generate the function from `FUZZY_RULES`)

**Comment by benoit74** [comment]
I'm referring to this rewrite function: https://github.com/openzim/warc2zim/blob/9897db5202ad9e9b921d17525d6e67be0a5c874c/src/warc2zim/templates/wombat_setup.js#L34 (rewrite rules are already tested in Python, and I don't mind much to not test them again in JS)

**Comment by mgautierfr** [comment]
Indeed, forget about my previous comment.

Agree to test it.
