### ISSUE TITLE
Prevent dead links

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#23]
Following-up on #21, we want to create ZIM files without dead links. This is slightly different to WARC which focuses on fidelity with the original source.

Preventing dead links means:
* not including files with no content (0 bytes length)
* rewriting content to exclude links to missing articles.
* keeping links to external URLs

**Comment by ikreymer** [comment]
Yes, sometimes we also call this the 'web archive boundary' problem: what happens when a user hits the edge.
Is the desired behavior to replicate the behavior of `/catch/external`?
What should happen if a link is a 404 that is not external? (could be some dynamically created url)

**Comment by rgaudin** [comment]
@kelson42 should be able to answer.

For wikis, we remove links to same-wiki, non included articles and leave foreign links as is (could be blocked or not at runtime)

In zimit, the scope is fuzzy as one can scrape only a subset of a website (or multiples) 
so it's hard to tell.

We could say that for warc2zim, the WARC is our context and whatever is not included is a remote link, even if on same domain or visually a _next of kin_

**Comment by kelson42** [comment]
I believe I still miss a proper understanding of what is `/catch/external`... but I believe as well as we don't want/need any kind of SW based catching of external URLs (beside the one which can be specified in kiwix-serve).

The most important is that there is no internal dead links within the ZIM files (this is what zimcheck try to detect). Every URL which is not an internal link is an external link, ie. starting with a protocol (like `https://` for example) and which should just respect the online original.

**Comment by ikreymer** [comment]
> I believe I still miss a proper understanding of what is `/catch/external`... but I believe as well as we don't want/need any kind of SW based catching of external URLs (beside the one which can be specified in kiwix-serve).
> 
> The most important is that there is no internal dead links within the ZIM files (this is what zimcheck try to detect). Every URL which is not an internal link is an external link, ie. starting with a protocol (like `https://` for example) and which should just respect the online original.

The full urls from the web page are always preserved, so there maybe be many links that start with `https://`, they are rewritten in the service worker to be loaded internally.. The way that this would work is that the service worker can detect if a URL is not found, and render a proper response, which could be: an error page, a redirect confirmation message, or automatically redirect. It can also do different things based on url, filering by domain.. I'll see what can be done..

**Comment by ikreymer** [comment]
I think this should be resolved now as much as is possible. The redirect handling should be working now.
Of course, it is impossible to prevent things that are missing on the live site.. Bouquineux has some PDFs that are 0-length/blank for example

**Comment by rgaudin** [comment]
Well there are a couple things we could know and act upon:

- Blank entries. For those we have a header article but no data. We know that those URLs leads to nothing. We could remove *links to those*
- Not-in-WARC but within the *request*. The request here depends on the `--include-all` or `--include-domain` argument. I don't think we can infer a generic behavior for this so we could have a `--missing-links [pass|ask|fail]` option to decide at creation time about the wanted behavior for this. Ideally, that could be superseded on a reader to a different behavior.
- Not-in-WARC and outside request. This will let them pass yet allow kiwix-serve or else to capture those. 

Removing links would be only limited to HTML links and not JS events or whatever but it would already handle a good chunk of this use case.

@kelson42 ?

**Comment by rgaudin** [comment]
Following-up on yesterday's discussion.

## Blank entries

We agree this is a very rare use case that appeared with Bouquineux but that we don't expect to see much.
It's a bug on the source website and the question is what should we do with those buggy files?
- Leave them as is (create no-content entries in ZIM). That's the closest to online experience but zimcheck is not happy. 
- Don't write ZIM articles for them. That's what we have in codebase. If we have links to those, they won't be served by the ZIM file (either fail or go online)
- Don't write ZIM articles **and remove links to them**. That would require HTML rewriting and would only concern pure-html links, not JS-fired events changing the location.
Another downside of this come from the Bouquineux example where links are to PDF files and visually appear as clickable icons. Removing the links here would mean having stuff that look like clickable items (PDF icon – which work for other books) but do nothing. This is arguably an equivalently poor behavior.
Additional issue is the fact that removing links `<a />` node, might break the styling of stuff. Manipulating the `href` might also be hazardous.

My current opinion on this is: keep current behavior: we don't write articles to ZIM but don't rewrite the links.

## External links in mwoffliner

In mwoffliner/wikipedia we have a fixed environment and made some choices:
- the target (source wiki) has clear boundaries. It's the articles set of the Wiki.
- we apply or not a selection on this articles list ; meaning excluded content to which there should be links.
- links that are not internal wiki links are external.
- red-links (links to non-existing articles – in the source wiki) are removed because there's zero value in having links there. It's visible on mediawiki so that people can create those articles.
- external links are kept as is. In an offline situation, it leads to an error and when online, it shows the online version. This is dependent on the reader (popup/blocking)
- links to internal articles that are not included (out of selection) are removed. It makes sense in the wikipedia context where every article is *bonus content* in itself but each article is independent. Having those as external links could be a valid choice as well.

Note: mediawiki is quite standard in that the experience is known, expected and limited. It's thus relatively easy to make assumptions about how rewriting stuff will affect the resulting ZIM.

## External links in warc2zim

First thing to recall is that warc2zim works off WARC files which are completely free in terms of bundled content. It could be a complete website, multiple websites (not talking about dependencies) or just cherry-picked pages from one.
That said, we know that for our use case (where we'll bundle the scraper and warc2zim), we'll do single, complete, websites (`all-links` crawl-type).

Contrary to mwoffliner, there is no *internal* vs *external* link concept here. Alls links are links and the only concrete treat is that some are inside the warc/zim, some are not.

Those that are inside are de-facto internal.

For those that are not, it's not clear. If you're browsing a website and the content of the *About* page is not in the ZIM, is it a missing internal-link or an external link?

One information that we have is the request to warc2zim where we specify the domains to include. From that we could say *this URL is for a requested domain, so a missing article means missing-internal and not external*.

## What to do with those links?

The question is the same for both *missing-internal* and *external* links, but the treatment might be different:
- Do nothing and let the reader do its thing (popup/block/pass)
- rewrite HTML to remove links to internal-missing

Contrary to mwoffliner, we can't just change the link style (add an icon in front implying it's external/online) as this would break most websites.

As it appear not possible to make a clear choice because it depends on the user's wishes, maybe we should consider asking the user.
And that should not be the ZIM's responsibility but the reader's. IMO, readers should catch external (both meaning here) URLs (they already do) and ask the user what to do (they already do – most of them) and they should be a little smarter by offering a sort-of *remember this choice* option (some readers do) so that the experience stays easy.

One thing here is the fact that kiwix-serve is not much considered a reader because of its client-server nature. So we kept it stateless and moved all decisions to the server launcher. If kiwix-serve blocked all external links by default and offered user a choice about what to do and recorded some user-prefs in a cookie, it would give more flexibility on this.
Going this way would mean endorsing the reader-status of kiwix-serve and open the door for additional reader-like feature like search customization or language related stuff. But **it's a completely different topic**

@kelson42 @ikreymer what are your takes on this?

**Comment by rgaudin** [comment]
Closing in favor of #65
