### ISSUE TITLE
Add support for redirection in `meta http-equiv`

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#237]
It is possible to redirect a page with a `meta http-equiv`:

```
<meta http-equiv="refresh" content="3;url=https://www.mozilla.org" />
```

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#http-equiv

So far, Zimit2 does not rewrite these links which are hence not leading to content inside the ZIM.

These links should be considered for rewrite as well.

The result will of course depend on wether the redirect target is present inside the WARC/ZIM or not.

Which in turns depends on how the WARC has been built (i.e. did the system which built the WARC waited long enough to have the redirect target captured as well?) but this is beyond the scope of this issue / warc2zim. warc2zim must just ensure to consider these URLs for rewrite.

**Comment by benoit74** [comment]
I do not consider this is mandatory at all for Zimit2 release

**Comment by Jaifroid** [comment]
> I do not consider this is mandatory at all for Zimit2 release

Agreed. It was an issue with the www.ready.gov ZIMs, but it did not affect systems reading the ZIM with the Replay ServiceWorker, because AFAIK the redirect was caught by the Service Worker (I may be wrong about that).

For zimit2, it's fine to deal with this empirically.

**Comment by kelson42** [comment]
> I do not consider this is mandatory at all for Zimit2 release

@benoit74 Not a regression in comparison to Zimit1? It‘s also a pretty common scenario.

**Comment by benoit74** [comment]
Nope, not a regression AFAIK, it wasn't working in Zimit1 (hence the issue mentioned by Jaifroid on www.ready.gov)
