### ISSUE TITLE
Doesn't work over HTTP

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#24]
I am classifying this as a bug because of its impact.

The [spec](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) clearly state that SW only works over HTTPS (and HTTP on localhost)

> You’ll also need to serve your code via HTTPS — Service workers are restricted to running across HTTPS for security reasons. GitHub is therefore a good place to host experiments, as it supports HTTPS. In order to facilitate local development, localhost is considered a secure origin by browsers as well.

Our main use case for those ZIMs being through [kiwix-hotspot](/kiwix/kiwix-hotspot) in an offline kiwix-serve, we need to find ways to make this work.

**Ideas**:
* Serve the hotspot over HTTPS and find a way to instruct users to allow the self-signed certificate. Might not be possible on some browsers/mobile.
* Use a custom kiwix-owned domain (`hotspot.kiwix.app`), get a recognized-CA-signed certificate for it and place it in the hotspot. As this is basically allowing anybody to impersonate that domain, that might be forbidden by CA contracts and get the certificate revoked.

**Comment by kelson42** [comment]
@ikreymer Do you have any idea to deal with this serious problem?

**Comment by ikreymer** [comment]
Yes, this is tricky.. I don't have any good solutions.. Probably distributing a certificate, maybe even generated with letsencrypt (but it doesn't last very long) is best option.. I'll think about it more..

**Comment by rgaudin** [comment]
#43 should be able to detect this scenario and display something custom when that happens, offering to try the HTTPs version of the same URL.

We'll make it super clear and user-friendly and play down the security warnings but that's a content issue not related to this. We just need the stub here.

**Comment by kelson42** [comment]
@rgaudin Do we want to the detail of the "tutorial" in the ZIM itself or in kiwix-serve?

**Comment by rgaudin** [comment]
In the ZIM for now as the ZIM provides the SW but that's something we shall consider in the kiwix-serve evolution discussion
