### ISSUE TITLE
youtube.fuzzy.replayweb.page/embed/fCAhUkOePf4 should not be front

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#241]
Following closing #108 I wanted to test if it work better… and it does but it seems we save „articles“ as front and we should not, see https://dev.library.kiwix.org/viewer#mes-quartiers-chinois_fr_all_2024-03/youtube.fuzzy.replayweb.page/embed/fCAhUkOePf4

**Comment by benoit74** [comment]
Duplicate of #240 I just opened and mentioned when closing #108 (this time I did it in the right order ^^ but it looks it is still not sufficient ^^)

**Comment by kelson42** [comment]
@benoit74 Sorry, I'm blind
