### ISSUE TITLE
Warc2zim2 is not sufficiently resilient to statical URL rewrite issues

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#247]
In warc2zim, we rewrite URLs statically in documents (HTML, JS, CSS, ...) so they point to the right ZIM entry.

While this is a mandatory action for proper operation, it might fail on some occasion especially when the source document is incorrect.

For instance, following HTML code is impossible to rewrite properly: `<a href="http:"></a>`

Currently, when such a situation occurs the scraper is stopped with a failure.

This is not correct, since we know that a bad source document cannot be recovered at all (or at least we do not want to).

As a consequence, we need to ensure that any URL rewriting issue is just raising a warning (probably only in DEBUG level) inside the log but not failing the WARC conversion or the WARC item conversion. We just need to keep the URL as-is.

**Comment by kelson42** [comment]
@benoit74 My feeling is that this feature request is not a good ide. The given example is an invalid URL and can/should simply be identified as such.

**Comment by benoit74** [comment]
> Why not check that URL is syntaxically correct and just ignore rewritting error in such a scenario?

This is exactly the intent of this issue. Currently we raise an error because we fail to parse the URL (because it is not syntaxically correct) and we stop the scraper. We should in fact just ignore rewritting of this specific URL.

**Comment by benoit74** [comment]
Fixed by https://github.com/openzim/warc2zim/pull/249
