### ISSUE TITLE
 Move from multiple `--tags` flags to one single `--tags` flag

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#265]
Currently, when the user wants to specify multiple ZIM tags, he has to specify multiple time the `--tag` parameter like in `warc2zim --tags "Quality Assurance" --tags "Another TAG"`

This kind of thing is not supported by the Zimfarm and is not in line with other scrapers behavior.

We hence want to move to one single `--tags` flag which might contain a CSV value like in `warc2zim --tags "Quality Assurance,Another TAG"`. Commas are not expected to be used in tag values.

NOTA: this is a breaking API change ... so better done in 2.0.0

**Comment by benoit74** [comment]
See https://github.com/openzim/warc2zim/pull/267#discussion_r1611585140, values must be separated by semicolons.

**Comment by kelson42** [comment]
Seems to be fixed!
