### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#286]
This is the default version on Ubuntu 24.04.

**Comment by benoit74** [comment]
We are already using Python 3.12 (and only Python 3.12): https://github.com/openzim/warc2zim/blob/4ddbea3f7b7b0f4c47ff225ff02f7ad1ec8efa50/pyproject.toml#L8

It is just not yet released in Pypi, so the Pypi badge in README.md is not yet updated
