### ISSUE TITLE
Parse HTML to determine title and possibly language

### ISSUE THREAD

**Issue by ikreymer** [openzim/warc2zim#29]
Add HTML parser to:
- parse the `<title>` from HTML pages
- parse the language from the main page only from `<html>` or `<meta>` tags, if not specified.. (though have to read WARC first to find main page, so may be slightly slower to search for it)

**Comment by kelson42** [comment]
I believe this would probably be better to implement such a feature ins python_scraperlib.

**Comment by rgaudin** [comment]
The title thing is already available in scraperlib. Opened https://github.com/openzim/python_scraperlib/issues/35 for the language thing. As written, it might be wise to look at Content-Language in headers…

**Comment by ikreymer** [comment]
I implemented this here, parsing language and also favicon: https://github.com/openzim/warc2zim/blob/metadata/src/warc2zim/main.py#L347

For title, I have:
https://github.com/openzim/warc2zim/blob/metadata/src/warc2zim/main.py#L450
I see for title there is something very similar in scralerlib, could use that..

You can copy the language and favicon implementation into scraperlib if you'd like..

The title extraction is run for every page, while language + favicon only once for main page, so probably better to keep them separate..
