### ISSUE TITLE
Drop `integrity` attribute in `<script>` HTML tags

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#298]
See https://github.com/openzim/zim-requests/issues/1025

We cannot click on the navigation tree on the left (at least, it does not expand / collapse sections properly).

Broken ZIM is available at https://dev.library.kiwix.org/viewer#dart.dev_en_all_2024-06

**Comment by benoit74** [comment]
It looks like we have at least a problem linked to the "integrity" attribute of the `<script>` tag loading some JS code. Might well explain the issue.

**Comment by kelson42** [comment]
I should learn what the "integrity" attribute is about first...

**Comment by kelson42** [comment]
@benoit74 Following documentation https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity you might remove it from "link" nodes as well?!
