### ISSUE TITLE
Title and favicon from source should be displayed

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#30]
Main frame should set the correct source title and favicon.

See #29.

**Comment by kelson42** [comment]
If the title has been fixed, it seems the favicon is not properly available.

See this screenshot. On the left kiwix-serve, on the right the original web site.

![image](https://user-images.githubusercontent.com/1029718/97287774-4424bb00-1845-11eb-8260-fff5a13f55d7.png)
