### ISSUE TITLE
Add support for MediaSource requests

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#329]
https://github.com/openzim/zimit/issues/323 has shown that youtube player has been updated to use new kind of requests for video content.

For now, a fix is implemented in wabac.js (and embedded in Browsertrix crawler in our case) to force Youtube player to fallback to previous requesting mode.

We however have no idea how long this workaround will be maintained by Youtube, and we might well need a way to properly handle the new requesting mode.

If I understood correctly, the component doing the requests is in fact not specific to Youtube but it is simply the [MediaSource](https://developer.mozilla.org/en-US/docs/Web/API/MediaSource) API, now supported by major browsers.

We hence have:
- many video players (Vimeo, ...) which will probably soon (or already have) transition to MediaSource API to request video content
- no way to properly handle the MediaSource requests in warc2zim / libzim / ...

This is a medium term issue but a very concerning one.

**Comment by ikreymer** [comment]
The way this is handled more generally in wabac.js is with DASH and HLS manifest rewriting, those are existing standards for video streaming, and have been in use for many years. This is a good fallback, but some platforms YouTube and Vimeo, don't quite use the standard format, and specifying stream chunks in other ways. Capturing and replaying content with MediaSource is already possible/happening, its just less predictable and often requires additional work.

**Comment by benoit74** [comment]
Thank you for these details! Closing this then since it looks we might have probably little to do in warc2zim for now
