### ISSUE TITLE
Use `software` from `warcinfo` record to set `Scraper` metadata

### ISSUE THREAD

**Issue by benoit74** [openzim/warc2zim#357]
Currently, scraper sets the `Scraper` ZIM metadata based on warc2zim version + an optional scraper suffix (usually passed by zimit with zimit version + browsertrix version).

This is not the optimal solution because WARC file already contain one (usually) `warcinfo` record which contains the browsertrix version in a `software` property.

We should prefer to use this information rather than fetching it indirectly in Zimit, especially since begining with https://github.com/openzim/zimit/issues/301 the WARC processed might come from a browsertrix version different than the one packaged with zimit. Even without this issue, it would allow to use any WARC harvester and still automatically have a proper `Scraper` metadata.

**Comment by rgaudin** [comment]
Is this a mandatory record? Question being should we handle a fallback?

**Comment by benoit74** [comment]
This is not a mandatory record. And it is allowed to have multiple records (typically one per warc.gz, with usually always the same information). It is however a standardized one. More details here: https://iipc.github.io/warc-specifications/specifications/warc-format/warc-1.0/#warcinfo (I forgot to add this link in original comment, sorry).

Browsertrix crawler is always creating one record with only `software` + non-standard (AFAIK) `format`, e.g. `software: Browsertrix-Crawler 1.2.4 (with warcio.js 2.2.1)\r\nformat: WARC File Format 1.1\r\n`

I don't think we need a fallback, but we need to take into account that it can be missing for some random warc.gz, in which case we might have only zimit + warc2zim version in `Scraper` metadata, which is not a problem AFAIK. And simply ignore all subsequent `warcinfo` if we already have found the `software`.

**Comment by rgaudin** [comment]
OK ; given we'll only fallback on non-browsertrix (_pure_ warc2zim usage) crawls, we should only include warc2zim in this case as to not add misleading info.

**Comment by benoit74** [comment]
More exactly we will only include warc2zim if the warc does not have proper `software`. If there is a `software` specified, even in __pure__ warc2zim usage, then adding this information in the ZIM is relevant from my PoV. E.g. a warc made with browser extension and transformed to a ZIM with warc2zim should if possible container the browser extension info in `Scraper` metadata.

**Comment by rgaudin** [comment]
hence the word _fallback_ 😀
