### ISSUE TITLE
i18n user-facing strings

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#36]
At least the not-found page present English text strings to user. We should have i18n for those and at least one translation stub (french). Instructions on how to set-it up is visible on /openzim/youtube repo.

**Comment by ikreymer** [comment]
I think this should also be handled by kiwix-lib, ideally, as it is part of the replay system.
For the service worker error, #43 suggests a way that this would be done via kiwix-lib.
For not found page, how does this work currently? Is there a localized version of the not found page in kiwix-lib now?
If so, probably should find a way to just load the existing error text to be consistent.

**Comment by rgaudin** [comment]
I think there's a misunderstanding about what kiwixlib is for. First kiwixlib, as its name suggests is for kiwix tools to use. Zim readers don't need kiwixlib, they only need libzim or any implementation of the spec.
Putting anything in kiwixlib implies it's not available for non-kiwix readers and translating strings from a scraper should be in the scraper. If you have the strings in your scraper repo, you're responsible for setting up the translation.

Second, we don't modify kiwixlib for every scraper. What we're doing with warc2zim is different enough from other scraper that we'll have to add changes to the architecture and potentially the Zim spec. kiwixlib should be content agnostic.

Also, we're talking about a very limited set of strings here ; and I provided a link on how to implement that easily. 
Should this eventually move elsewhere, it would be very easy to remove from here but until then, this should be internationalized.

**Comment by ikreymer** [comment]
The youtube scraper has [text specific to youtube](https://github.com/openzim/youtube/blob/master/youtube2zim/locale/fr/LC_MESSAGES/messages.po) (playlist, etc...)

> At least the not-found page present English text strings to user.

Unless I'm misunderstanding something, shouldn't it ideally just be the same as this page?
https://github.com/kiwix/kiwix-lib/blob/master/static/templates/404.html

How does this page get internationalized, or it doesn't currently?

Just want to make sure I understand - can copy that file into every ZIM and add i18n.

**Comment by rgaudin** [comment]
> The youtube scraper has [text specific to youtube](https://github.com/openzim/youtube/blob/master/youtube2zim/locale/fr/LC_MESSAGES/messages.po) (playlist, etc...)

Absolutely and this scraper has text specific to this scraper (not found string, service worker not working string, loading string – that is being replaced by visual one though, maybe others?). It's not much but it's English-only at the moment so should get i18n'd.

> Unless I'm misunderstanding something, shouldn't it ideally just be the same as this page?
> https://github.com/kiwix/kiwix-lib/blob/master/static/templates/404.html

Yeah it could. Others scraper usually create the webpages so we don't have dead links inside.
 
> How does this page get internationalized, or it doesn't currently?

kiwixlib and thus kiwix-serve doesn't do i18n at the moment.

> Just want to make sure I understand - can copy that file into every ZIM and add i18n.

Not sure what *copy* means here. There's no problem with the current styling of this. We just want all UI strings to be internationalized and the localization applied at ZIM creation time (using the language from `--lang`).
