### ISSUE TITLE
Random offers binary files

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#37]
This is a tracking ticket following discussion on #17.

Current agreement is that the way forward should be dictated libzim's decisions on how to address this in a namespace-less context. Once this is settled, we'll adjust.

**Comment by kelson42** [comment]
Basically a duplicate of https://github.com/kiwix/kiwix-lib/issues/404. This will be fixed in the Kiwixlib.

**Comment by kelson42** [comment]
@mgautierfr We don't have talk about this problem during the last weekly meeting, but this is something as well to fix before definitly closing libzim_next C++ effort.

**Comment by kelson42** [comment]
@mgautierfr I believe https://github.com/openzim/libzim/issues/397 won't be able to fully fix this problem right?

**Comment by kelson42** [comment]
@mgautierfr Does this ticket needs https://github.com/openzim/libzim/issues/384? But in that case I worry about the simple non-xapian suggestion system to fail.

**Comment by kelson42** [comment]
Warc2zim will have to set the front articles

**Comment by kelson42** [comment]
@rgaudin I think the code in libzim gith master alows you now to fix this at warc2zim level.

**Comment by rgaudin** [comment]
It's not in pylibzim. Depends on https://github.com/openzim/python-libzim/issues/93

**Comment by kelson42** [comment]
@rgaudin Can we close this issue? Or fix what is left in this repo?

**Comment by rgaudin** [comment]
Random being linked to the title index, I suppose we need https://github.com/openzim/libzim/issues/642 in the libzim for it to work as planned so this would await a future warc2zim release using python libzim 1.1 (libzim 7.1)

**Comment by kelson42** [comment]
@rgaudin Good, then we should be able to close it soon. I have created a 1.4.0 milestone.

**Comment by rgaudin** [comment]
Seems OK now as we rely on default libzim behavior for hints which won't set front_article on binaries.
Confirmed behavior with _fas-military_ (single HTML index, many PDF) and it seems to operate as expected.

_fas-military_ do include a couple of undesired pages through random: images that were 404 when scraped so we have an HTML 404 page displayed instead. That's content/scrape related.

We may want to discuss what we would ideally want here. Imagine those requests raised an HTTP 404 (haven't checked). Do we want to **unconditionally** consider that `404` should not be front article? I'd prefer not but it's debatable.
