### ISSUE TITLE
HTML entities are not removed from ZIM article titles

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#38]
See for example "Jean Aicard - L&apos;Illustre Maurin ( EPUB et PDF gratuits )" in bouquineux.zim which gives `Jean Aicard - L&apos;Illustre Maurin ( EPUB et PDF gratuits )` in kiwix-serve suggestions (one time chosen).

**Comment by rgaudin** [comment]
- [the page](http://bouquineux.com/index.php?telecharger=1379&Aicard-Notre-Dame-d_Amour) title doesn't encode this.
- I checked the WARC and it's content doesn't have it encoded.
- the python code doesn't encode it neither.

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Jean Aicard - Notre-Dame-d'Amour ( EPUB et PDF gratuits )</title>
<META NAME="Description" CONT
```

I've looked at kiwixlib quickly and we don't appear to do much there neither. The suggested list items are not encoded neither so it seems to be solely related to the taskbar JS:

```javascript
jk( "#kiwixsearchbox" ).autocomplete({

  source: "{{root}}/suggest?content={{#urlencoded}}{{{content}}}{{/urlencoded}}",
  dataType: "json",
  cache: false,

  select: function(event, ui) {
  jk( "#kiwixsearchbox" ).val(ui.item.value);
  jk( "#kiwixsearchform" ).submit();
  },

  });
```

[head_part.html](https://github.com/kiwix/kiwix-lib/blob/5f8c0998291d0778887373355bb6b1c5a345ed2c/static/templates/head_part.html#L9)

@mgautierfr can maybe explain with we use `{{#urlencoded}}` here?
