### ISSUE TITLE
`wombatSetup.js` floods console with `urlRewritten:` messages

### ISSUE THREAD

**Issue by Jaifroid** [openzim/warc2zim#404]
Lately, the `wombatSetup.js` included in recent Zimit2 ZIMs is flooding console with messages. In a single page load, I'm seeing ~150 `urlRewritten` messages like those seen in the screenshot:

![image](https://github.com/user-attachments/assets/34216f58-28f5-4230-9be8-c438af108143)

This makes debugging in my JS apps rather difficult, and means that important messages from the app itself are hard to see.

Would it be possible to remove these comments from versions of the app pushed to production? While I can filter out comments from wombatSetup, it's a pain to have to set up the filter each time I want to look at console, and in any case, it's not a good idea for masses of comments to be output by any app, as it slows down running of the app if it's having to spend CPU cycles on logging.

Thanks!

**Comment by benoit74** [comment]
As a side note, these are debug messages, so you can filter them out with just the log level. I don't mind to remove them, but this is going to have drawbacks obviously. No strong opinion on where the balance should be.

**Comment by Jaifroid** [comment]
Thanks @benoit74. The problem is that my apps mostly use debug-level logging as well, so messages that help me debug become needles in a haystack. What I'm suggesting is that these debug messages should be removed in production versions of warc2zim only (they can be removed automatically in the bundler). They can of course remain in development versions.

**Comment by Jaifroid** [comment]
PS It would be fine if it were a single summary message per page load, but easily having 150-300 messages every time I click on a new link is a bit... excessive! Obviously, I'm uniquely affected because my apps are written in JS, so JS logging is vital in my dev process.
