### ISSUE TITLE
Cold direct links are not working

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#41]
Accessing a direct link to a warc2zim-made article without going through the ZIM homepage first doesn't work : the browser offers to download the raw content as it is served as `application/octet-stream`.

The mime-type is purposely not `text/html` in order to prevent kiwix-serve from injecting the taskbar.

Although this visual consequence of appearing as a download can be fixed by changing the MIME-type ; it would not resolve this ticket as there is another problem:

The service worker is not registered and thus, if we had the correct MIME, the browser would only parse it and try to access any other resource (images, css, js, etc) from the actual remote URLs, resulting in either bandwidth usage or a broken page.

This is because the current code registers the SW in the homepage so skipping the homepage means no SW handling at all.

This cold-direct-link use case is **very important** and we can't change it because there are many solution integrator depending on it. The first ones coming to my mind are [kiwix-hotspot](https://github.com/kiwix/kiwix-hotspot), [Internet In a Box](https://github.com/iiab/iiab) and [OLIP](https://gitlab.com/bibliosansfrontieres/olip)

**Comment by kelson42** [comment]
This is indeed an important problem we have here. For the moment, I don't believe there is an elegant way to fix the problem only by tweaking the ZIM content. Therefore I believe we well have somehow to define a formalism so the reader can know that there is something to absolutly do before rendering an HTML content (here secure that the SW is properly setup).
