### ISSUE TITLE
Errors loading on android

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#45]
Thanks to https://github.com/kiwix/kiwix-android/pull/2259, the SW is now running inside kiwix-android. Note that the main change is that the custom scheme and netloc is now `https://kiwix.app/`.
So a regular `index.html` article would be at `https://kiwix.app/A/index.html`

The basicsw.zim file loads properly. warc2zim created ones gets stuck at the loading message.

Here's what I get with regular code base (took the sw.js from latest PR though)

```
index.html:6 Inside index.html
index.html:8 window.mainUrl https://isago.ml/
VM17 load.js:1 inside load.js
VM17 load.js:3 inside load.js main()
VM17 load.js:9 SW support present
VM17 load.js:11 creating worker...
VM17 load.js:13 created Worker {onmessage: null, onerror: null}
VM17 load.js:15 window.location.href https://kiwix.app/A/index.html
VM17 load.js:19 Name kiwix.app
VM17 load.js:21 registering SW
sw.js:17 ww init
sw.js?replayPrefix=&root=kiwix.app:17 sw init
VM17 load.js:23 registered
VM17 load.js:33 posting message from worker
sw.js?replayPrefix=&root=kiwix.app:33 Activate!
VM17 load.js:26 worker received mesage MessageEvent {isTrusted: true, data: {…}, origin: "", lastEventId: "", source: null, …}
VM17 load.js:28 received collAdded going from https://kiwix.app/A/index.html to https://isago.ml/
(index):6 Inside index.html
(index):8 window.mainUrl https://isago.ml/
Navigated to https://kiwix.app/A/index.html
Navigated to https://kiwix.app/
```

Note the last two lines (not traces but browser's message). The browser gets directed to `https://kiwix.app/` instead of the correct URL.

At this point the SW looks properly registered for `kiwix.app/A`.

If I **manually** go to `https://kiwix.app/A/isago.ml/` (the homepage being `https://isago.ml/`), I get the homepage and everything works as expected.

![screenshot-2020-08-07_14 01 57 762](https://user-images.githubusercontent.com/57929/89643667-92fe2c80-d8b6-11ea-8d52-799faaa6e5bb.png)

I eventually figured out that the problem is with the `mainUrl` that isn't ready for such a URL and doesn't get the regular treatment it should. The following fixed it:

```javascript
window.location.replace("/A/" + window.mainUrl.replace("https://", ""));
```

I don't know if the URL transformation should happen or if that should be handled elsewhere in the worker ; I'll let you do the proper investigation. Here's my fixed [zim file](http://tmp.kiwix.org/myisago.zim)

**Comment by ikreymer** [comment]
Ah yeah, the logic there is expected it to be `<zimname>/A/index.html`, that can be fixed.

But, is that the intended url, eg. all zim files loaded from `https://kiwix.app/A/index.html` and not `https://kiwix.app/<zimfile>/A/index.html`

I think that should still work, but want to double-check cacheing issues if all zim data is loaded under the same path..

**Comment by kelson42** [comment]
IT is impossible to make any assumption about the URL to load a ZIM content up to what is in the ZIM itself, this means the part starting with the namespace.

**Comment by rgaudin** [comment]
@ikreymer is this possible to make it work using only relative knowledge?

**Comment by ikreymer** [comment]
Yes, hopefully it should be fixed with the above PR.

**Comment by rgaudin** [comment]
Reopening, the attempted URL still includes the scheme so the initial redirection fails.

```
ww init
sw.js?replayPrefix=&root=kiwixapp:17 sw init
sw.js?replayPrefix=&root=kiwixapp:33 Activate!
VM17 load.js:38 final: https://kiwix.app/A/https://isago.ml/
Navigated to https://kiwix.app/A/index.html
Navigated to https://kiwix.app/
```

The *final* should be `https://kiwix.app/A/isago.ml/`. So there's an extra `https://` here.

**Comment by ikreymer** [comment]
Hm, the service worker should handle both correctly, with `https://` and without.. perhaps the service worker has not been updated somehow? Maybe its another issue with being root.. will check..
