### ISSUE TITLE
Should ReplayWeb.page be bundled in the python package?

### ISSUE THREAD

**Issue by ikreymer** [openzim/warc2zim#5]
Currently, warc2zim downloads a fixed version of https://www.npmjs.com/package/replaywebpage
every time it is run, with an option to override the version.

This means that, if there is no internet connection, warc2zim could fail if it can't connect to https://cdn.jsdelivr.net/ when running.

But perhaps a better solution is to add replayweb.page viewer to the python warc2zim package, eg. during `python setup.py install`, so that the default version is always available?

That way, a released warc2zim package could be more self-contained after it is installed.

Or keep current behavior?

**Comment by ikreymer** [comment]
After discussion: yes, will add to package at build time (setup.py)

**Comment by kelson42** [comment]
Not sure to understand properly, but would have been nice to have this stuff fixed within a linked PR and then closed. This ticket could have been mutated to "enhancement".

**Comment by rgaudin** [comment]
No there's already a Pypi package ticket. This was just a question regarding what to include in that package.
