### ISSUE TITLE
Internal tags missing

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#51]
Tags seem not supported at all:
* we should be able to customize the ZIM tags
* we have js in the M/Tags, see https://kiwix-dev.webrecorder.net/bouquineux/M/Tags
* Hidden tags should be set properly like _index and _sw, see https://wiki.openzim.org/wiki/Tags

**Comment by rgaudin** [comment]
>     * we should be able to customize the ZIM tags

It's the case using `--tags`
>     * we have js in the M/Tags, see https://kiwix-dev.webrecorder.net/bouquineux/M/Tags

Seems to be specific to this ZIM. will check.

>     * Hidden tags should be set properly like _index and _sw, see https://wiki.openzim.org/wiki/Tags

OK, that we forgot.

**Comment by rgaudin** [comment]
Some internal tags should be set:

* `_ftindex:yes`. As we default to `eng` if we don't have a language, a full-text index is always created.
* `_category:other`

**Comment by ikreymer** [comment]
Is it just these two: `_ftindex:yes` and `_category:other`? Maybe also add a tag for `_sw:yes` ?
