### ISSUE TITLE
kiwix-serve taskbar displayed in middle of page

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#52]
At https://kiwix-dev.webrecorder.net/lesfondamentaux/A/lesfondamentaux.reseau-canope.fr/a-propos.html

![image](https://user-images.githubusercontent.com/1029718/90664253-0571f380-e24b-11ea-8c67-8c5be01efd48.png)

Maybe the video should be there?

**Comment by ikreymer** [comment]
Should be fixed now, and in the PR
