### ISSUE TITLE
Should warc2zim pick a default url if none is specified

### ISSUE THREAD

**Issue by ikreymer** [openzim/warc2zim#6]
Currently, the `-u` flag is used to specify a starting url. If none is provided, then the result will not be a working ZIM.

I think there are two options:
1) Make the -u flag option required. A URL must always be specified.
2) Attempt to determine a default URL by picking the first text/html found in the WARC file. This is of course not guaranteed to work, but is a good default/option to try.

My preference would be for 2) as it makes testing with smaller WARCs easier also.
What do you think?

**Comment by rgaudin** [comment]
Yes, a default to the first `text/html` entry is OK although it would often not be satisfying. Up to the user to specify it if not happy with that default.
