### ISSUE TITLE
Tweak the rendering with custom CSS

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#61]
Now that we have a few ZIM files made via ZIMit/warc2zim, we can see how well the scraping and ZIM file looks like. To some extend this is too accuratly mimicing the original web site even with things which won't work and will never work like formular (leave comment, search, etc...) and even a few other things which might be even simply not welcome.

I propose to allow to put a custom CSS which would apply to each page in the ZIM. We could do that with a parameter called `--customCss=[path|url]`.

For the moment, not a priority, just asking to (in)valide the idea.

**Comment by Popolechien** [comment]
> a few other things which might be even simply not welcome

Do you have an example?
I agree that forms can be misleading, but then what would appear instead? I honestly have no strong opinion but am curious as to what the options are.

**Comment by kelson42** [comment]
> I agree that forms can be misleading, but then what would appear instead?

There would be hidden, you would see the bacground instead.
