### ISSUE TITLE
Add a blocked domains list

### ISSUE THREAD

**Issue by rgaudin** [openzim/warc2zim#63]
Following-up on https://github.com/openzim/zimit/issues/31, it would be handy to have a list of domains that we unconditionally exclude because it's useless.

We can start, as suggested, with `*.doubleclick.net/` and `google-analytics.com/`.

Can be a list in the code or an external file that we load.

**Comment by kelson42** [comment]
I think this is a good idea, but we should (at least) rely on a project maintaining such a list. See for example https://github.com/anudeepND/blacklist

**Comment by kelson42** [comment]
Any reason to not consider this ticket as a duplicate of https://github.com/openzim/warc2zim/issues/63?
