### ISSUE TITLE
Site issue: manioc.org

### ISSUE THREAD

**Issue by ikreymer** [openzim/warc2zim#71]
Most of the content is query/search based, and likely hitting a crawler trap, exceeding limits when crawling.
Need to improve rules possibly.

**Comment by ikreymer** [comment]
The crawl was 1.1TB, mostly video (mp4 and flash). I don't know if its warc2zim, or the zim writer in general..
Is that a size of ZIM files that is normally supported?

**Comment by rgaudin** [comment]
We've never created a ZIM this large but the libzim itself should be able to handle such a size. The python libzim and warc2zim are too young of projects to make assumptions about their capabilities.
We'll keep the WARC files on athena for when we'll have time to investigate that in detail.

**Comment by kelson42** [comment]
We have achieved to do it https://farm.openzim.org/recipes/manioc.org and it seems to work pretty good https://dev.library.kiwix.org/manioc.org_fr_all_2022-07/A/index.html
