### ISSUE TITLE
Lots of duplicate in ZIMit created ZIM files

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#75]
https://tukasu.ml/search?content=lowtechmagazine.com_en_all_2020-10&pattern=wind+

**Comment by rgaudin** [comment]
OK, I've looked into it. 

Those search results are not duplicates as those points to different URLs. Notice the `?cid=xxx` part at the end.
We had slightly different articles for each. The difference is not user-visible as it's just a couple tokens in the JS code.

```diff
881c881
< <script type="text/javascript">var c943723d42e77e9214eb884a1d898za = '" method="post"><input type="hidden" name="entry_xid" id="comment-entry-xid" value="6a00e0099229e888330240a4af6ba2200b" \/><input type="hidden" name="token" value="1603454606-aa7f140d67163cc94e14365f2029acae31ef01e4:wTt1LAhCscC2NPwK" \/>';</script>
---
> <script type="text/javascript">var c943723d42e77e9214eb884a1d898za = '" method="post"><input type="hidden" name="entry_xid" id="comment-entry-xid" value="6a00e0099229e888330240a4af6ba2200b" \/><input type="hidden" name="token" value="1603454651-cafadf171666656757c3a54db349a6b1233b5ec4:LiHpmUt5ZECcHTb9" \/>';</script>
1327c1327
< var tp_comment_token = "1603454606-5959e044786019f9b527ec7ed62e927825de7c53:sYNvlYTrOucs0is2";
---
> var tp_comment_token = "1603454651-19e553c55052eddbcd70be5623f5a8833bfa0b28:ogATskHNtMeEgRmm";
```

Links with those `?cid=` parts exists in content and point to those articles. You can find those links on the original website:

* Go to https://www.lowtechmagazine.com/2019/06/small-wooden-wind-turbines.html
* Scroll down to the comments section
* Hover on the date next to a comment.

You'll find the culprit links there. As you'd probably guessed, this link's purpose is to create a permalink to the attached comment.

There is no bug in the scraping nor in the warc2zim. I suggest we update the `--exclude` regexp of the recipe to include all links with `?cid=` and that should fix the issue.

**Comment by kelson42** [comment]
@rgaudin Have you updated the recipe? Could we check it fixes the problem?

**Comment by rgaudin** [comment]
https://tukasu.ml/search?content=lowtechmagazine.com_en_all_2021-01&pattern=wind+
