### ISSUE TITLE
ZIM favicon is not properly set

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#77]
This is a follower to https://github.com/openzim/zim-tools/issues/200 (where you can find the problematic ZIM file).

`-/favicon` is a redirect `A/wiki.openzim.org/w/images/favicon.ico`. This does not respect the ZIM spec, see https://wiki.openzim.org/wiki/Metadata#Favicon

**Comment by rgaudin** [comment]
What's the problem exactly? The fact that it's a redirect? The spec says nothing about that.

By the way, the spec requests specific dimensions ; I believe it'd be wise to request a specific image format (PNG?)

**Comment by rgaudin** [comment]
Well I suppose `Every key is defined like an article` can be understood as a bare article. Can you answer the second question so I can maybe fix both at once.

I believe we have a new Type for meta entries in libzim_next also.

**Comment by kelson42** [comment]
@rgaudin I'm sorry about that, you are right the spec is respected (even if we could improve it).
