### ISSUE TITLE
Alternative idea: store WACZ files in ZIM (wacz2zim)

### ISSUE THREAD

**Issue by ikreymer** [openzim/warc2zim#81]
I wanted to suggest an alternative approach to warc2zim, a wacz2zim, which may address some of the issues raised in #80

Webrecorder is developing the WACZ format (https://github.com/webrecorder/wacz-format) and we have a stable release for it. The WACZ format bundles WARC files, indexes and page data inside a ZIP file. The format is specifically optimized for reading in the browser, and the wabac.js system is designed to read the WACZ file on-demand. Browsertrix-Crawler will soon be updated to generate WACZ as well.

An idea would be to simply put the WACZ file directly into the ZIM, along with the other file used by the wabac.js sw, and placeholder html. For example, an archive of a youtube page might look something like

```
A/youtube.com/watch%2F... - just contains the text and loaded only initially for redirect
A/replay/archive.wacz - all actual data will be read from this file
A/replay/sw.js
A/replay/topFrame.html
... (other supporting file part of current replay in templates/)
```

To support the existing redirect when no service worker is installed, and search , ZIM entries can still be added only for HTML pages, like `youtube.com/watch?...`. Since WACZ will already include a page list with extracted text, these entries can be generated from the WACZ pages file. These could just be bookmarks containing text + redirect and not the actual content. (Or, the actual content could also be used if want to rely on Xapian specifically for text extraction).

The advantages of this system would be that no custom loading, or fuzzy matching, would be needed.
The loading path and the conversion would be a bit simplified, since latest wabac.js and wacz format can simply be packaged into the ZIM. This will also support for prefix queries that wabac.js normally relies on for reading wacz files.
The client will make requests to archive.wacz with specific ranges, and it would just be a binary file as far as the readers are concerned.
This should significantly lower the maintenance burden on wabac.js-based replay in ZIM, and probably should have minimal impact for users.

The main disadvantage is perhaps compression, as wacz is using gzip for now, and contains warc files inside of it, which also use gzip. There is a proposal to support zstd for warc, and that may eventually be supported (though probably not too soon).
This would require zstd decompression in JS as well.

I don't know how much of an issue it is, or what compression gains there, especially from sites that are heavy on video/images. My guess is that it is less than on a text-heavy site like wikipedia where zstd probably offers significant improvements.

With this approach, the system would be able to use prefix search over the wacz and also cache data in the IndexedDB (on-demand). It would also be beneficial to clear out the IndexedDB when a WACZ-based ZIM is uninstalled -- this is similar to uninstalling the sw, but somewhat simpler, and cache size can be adjusted.

**Comment by rgaudin** [comment]
Thank you for this. I've skimmed through the [WACZ](https://github.com/webrecorder/wacz-format) *spec* and I kinda like it. My understanding is that you read+parse the index at the end of the ZIP file to *guess*/*map* the byte ranges of the actual data inside the WACZ.

My concerns are:
- throwing off most of what we did.
- having to go through all the in-zim design discussion again
- what about search? New libzim introduced segregation between record-content and indexed-data but this is tied to records. With this solution, we'd have only one giant record so that would mean no libzim search… No suggestion neither nor random for the same reason. I understand we could work around the search/suggest with *fake* (html redirect) records.

Also important is going further away from the ZIM format will.

That said, from a user perspective, the only drawback is (slightly?) larger ZIM files and (somewhat?) more CPU required while the maintenance burden seem to be greatly reduced.

Question: would this require specific code for in-zim at webac/replayer level?

**Comment by ikreymer** [comment]
> Thank you for this. I've skimmed through the [WACZ](https://github.com/webrecorder/wacz-format) _spec_ and I kinda like it. My understanding is that you read+parse the index at the end of the ZIP file to _guess_/_map_ the byte ranges of the actual data inside the WACZ.
> 

Yes, this works due to the property of ZIP files, and I based it on this library:
https://github.com/Rob--W/zipinfo.js which provides the JS implementation and explanation.

Since WARC files do not have a built in index, it is stored in the indexes/ directory (usually compressed main index and bin-searchable secondary index).

Everything is accessible with range requests into the wacz file.

> My concerns are:
> 
> * throwing off most of what we did.

Well, it would be removing some things, but not everything.
Anything related to parsing WARCs will probably be removed.
But everything related to the service worker handling, and most of the logic/UI in `templates/` would remain.

Would still keep the current UI (spinner, error messages, 404 page)

> * having to go through all the in-zim design discussion again

Right, would need to decide on how things are laid out in ZIM, but hopefully simpler

> * what about search? New libzim introduced segregation between record-content and indexed-data but this is tied to records. With this solution, we'd have only one giant record so that would mean no libzim search… No suggestion neither nor random for the same reason. I understand we could work around the search/suggest with _fake_ (html redirect) records.

Yes, so that was my suggestion, is creating 'placeholder' html entries in the ZIM for each page that is searchable, which if loaded will just redirect to the service worker, which is what it does now.

The WACZ will provide a list of pages in `pages/pages.jsonl` file which will contain entries like this:
```
{"url": "https://example.com/page.html", "title": "Example Page", "text": "all extracted text here", "ts": ...}
{"url": "https://example.com/another.html", "title": "Other Page", "text": "more text here", "ts": ...}
```

My idea would be to just convert these to ZIM entries: `/A/example.com/page.html`,
which would contain:

```
<html>
<head>
<script><!--check for SW and redirect--></script>
<title>Example Page</title>
</head>
<body>
all extracted text here
</body>
</html>
```

Then, I think it will probably work with the current Xapian text search, suggestions, random page, etc...

These would be the only other entries added besides the replay and the .wacz file.


> 
> Also important is going further away from the ZIM format will.
> 
> That said, from a user perspective, the only drawback is (slightly?) larger ZIM files and (somewhat?) more CPU required while the maintenance burden seem to be greatly reduced.
> 
> Question: would this require specific code for in-zim at webac/replayer level?

It should not, since it will just load the wacz over https like it does in any other case. Assuming standard `Range` requests work, that should be it. Would be less special code than now, and so would improve maintainence.

The custom stuff then is just the UI, since we are not using ReplayWeb.page UI but already have a custom one with spinner, localization, sw checks, etc...

**Comment by rgaudin** [comment]
OK, would it be possible to not store the extracted text in the pages.jsonl ? Unless I misunderstood something, this is full duplication of the complete *text* of the resource in the ZIM. When we'll feed that to xapian for its index, it's gonna be like 3 times in the ZIM file.

It would be better to loop over WARC records when we create those fake zim entries, extract the text and feed it to xapian (using the new `getIndexData` feature of libzim) and setting the title as well.

So I guess the question is more: can the search/suggest features of your replayer be completely disabled and thus remove the `title` and `text` from the pages.jsonl ?

I forgot another concern: the fact that WACZ is *your* format while WARC is much more *standard* and *adopted* and I believe that played some role in the previous decision.

**Comment by ikreymer** [comment]
> OK, would it be possible to not store the extracted text in the pages.jsonl ? Unless I misunderstood something, this is full duplication of the complete _text_ of the resource in the ZIM. When we'll feed that to xapian for its index, it's gonna be like 3 times in the ZIM file.

Yeah, I guess we could delete the text from the pages.jsonl, or not generate it there. (This features is still being worked on as part of webrecorder/browsertrix-crawler#2)

> 
> It would be better to loop over WARC records when we create those fake zim entries, extract the text and feed it to xapian (using the new `getIndexData` feature of libzim) and setting the title as well.

I'm not sure what getIndexData does, but the text that would be in pages.jsonl would be extracted from the live web page as rendered in the browser. This is not the same as just extracting text from the HTML, ideally will have better results for dynamic pages as it will get the text from the current rendering.

The pages.jsonl is also important because it lists what the top-level pages are, which is not necessarily every `text/html` resource. In fact, indexing everything that is text/html leads to lots of false positive (some ad iframe, some other resource that defaults to text/html on old servers, etc..).

It would be possible to just look at the pages.jsonl, and then lookup those URLs in the WACZ and use that as the input for the text search. But, then you would just re-extract the text that is already being extracted, but it is doable. (We need to add URL lookup in the WACZ still or just iterate over the WARCs, which is longer).

> 
> So I guess the question is more: can the search/suggest features of your replayer be completely disabled and thus remove the `title` and `text` from the pages.jsonl ?

The data is only used in the replayweb.page UI, so it won't be used in this custom UI. But as explained above, I think using it simplifies things, as it provides extracted text from the browser and title that can be plugged into whatever is needed in the ZIM, so less duplicate work.

> 
> I forgot another concern: the fact that WACZ is _your_ format while WARC is much more _standard_ and _adopted_ and I believe that played some role in the previous decision.

Partly for this reason, the WACZ file preserves the full WARC files in the ZIP. If the goal is to convert back to WARC from a ZIM, it would be simpler to get a WARC out from the ZIM using WACZ (just extract it), then what we have now, since the current system transforms the WARC records and drops some of them..

**Comment by rgaudin** [comment]
> Yeah, I guess we could delete the text from the pages.jsonl, or not generate it there. (This features is still being worked on as part of [webrecorder/browsertrix-crawler#2](https://github.com/webrecorder/browsertrix-crawler/issues/2))

OK

> > It would be better to loop over WARC records when we create those fake zim entries, extract the text and feed it to xapian (using the new `getIndexData` feature of libzim) and setting the title as well.
> 
> Yes, it would be possible to do that, but it may be extra work without necessarily any benefit.

Well not storing the same content multiple (3!) times is certainly beneficial.

> I'm not sure what getIndexData does exactly or if it would be helpful. The text that would be in pages.jsonl would be extracted from the live web page as rendered in the browser. This is not necessarily the same as just extracting text from the HTML, ideally will have better results for dynamic pages as it will get the text directly from what's rendered in the browser.

getIndexData is just something you provide the libzim so that it can index your Entry using a different input than the Entry's content. So Ideally we'd return the extracted text here for those *fake* redirections and benefit from full text indexing/search.
This browser-extracted text is very interesting (compared to source parsing). We should definitely index that.
Out of curiosity, how is it done? Is this just DOM manipulation to get text values from text nodes or is it something that the browser provides?

> The pages.jsonl is also important because it lists what the top-level pages are, which is not necessarily every `text/html` resource. In fact, indexing everything that is text/html leads to lots of false positive (some ad iframe, some other resource that defaults to text/html on old servers, etc..).

We don't want to get rid of the file but none of what you just mentioned requires anything but the URL.

> It would be possible to just look at the pages.jsonl, and then lookup those URLs in the WACZ and use that as the input for the text search. But, then you would just re-extract the text that is already being extracted, but it is doable. (We need to add URL lookup in the WACZ still or just iterate over the WARCs, which is longer).

Yeah I think the issue here is having a lower quality text (source vs document)

> > So I guess the question is more: can the search/suggest features of your replayer be completely disabled and thus remove the `title` and `text` from the pages.jsonl ?
> 
> The data is only used in the replayweb.page UI, so it won't be used in this custom UI. But as explained above, I think using it simplifies things, as it provides extracted text from the browser and title that can be plugged into whatever is needed in the ZIM, so less duplicate work.

I think you misunderstood the issue. Those title and text are great but since we won't use your custom suggestion/search feature, this will be put in the ZIM index. With it in the index, that's a potentially quite large duplication.
An option would be to remove it from the WACZ (keeping only urls) once this is is the ZIM but I'm not sure how practical that is.

> > I forgot another concern: the fact that WACZ is _your_ format while WARC is much more _standard_ and _adopted_ and I believe that played some role in the previous decision.
> 
> Partly for this reason, the WACZ file preserves the full WARC files in the ZIP. If the goal is to convert back to WARC from a ZIM, it would be simpler to get a WARC out from the ZIM using WACZ (just extract it), then what we have now, since the current system transforms the WARC records and drops some of them..

@kelson42 can respond to that but I think the idea is more in reusing and leveraging existing formats and tools rather than competing with them, especially if that brings maintenance on our shoulders. WACZ is compatible with this IMO as this is just an additional layer on top of WARC.

**Comment by ikreymer** [comment]
> getIndexData is just something you provide the libzim so that it can index your Entry using a different input than the Entry's content. So Ideally we'd return the extracted text here for those _fake_ redirections and benefit from full text indexing/search.

Ah, I see, that could work then. I wasn't sure if the default Xapian text/html extraction would just take care of it as well,
if its a fake entry, but yes, can just pass the text/title to zimwriter a different way if needed.

> This browser-extracted text is very interesting (compared to source parsing). We should definitely index that.
> Out of curiosity, how is it done? Is this just DOM manipulation to get text values from text nodes or is it something that the browser provides?

Yes, the browser has an [API to return the DOM entries as JSON](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getDocument). From that, all of the text nodes can be filtered out recursively:
https://github.com/webrecorder/browsertrix/blob/pywb-instance/simple-driver/index.js#L234

> I think you misunderstood the issue. Those title and text are great but since we won't use your custom suggestion/search feature, this will be put in the ZIM index. With it in the index, that's a potentially quite large duplication.
> An option would be to remove it from the WACZ (keeping only urls) once this is is the ZIM but I'm not sure how practical that is.

Ok, yes, that's definitely doable - we could read the pages.jsonl and remove that and readd the file, or simply preprocess before creating the zip. The WACZ is just a zip file after all, I think it should be ok to update it.
The WACZ support for browsertris-crawler is currently being worked on, so there's definitely an opportunity to make sure it supports this use case as it is being added.

> 
> @kelson42 can respond to that but I think the idea is more in reusing and leveraging existing formats and tools rather than competing with them, especially if that brings maintenance on our shoulders. WACZ is compatible with this IMO as this is just an additional layer on top of WARC.

Agreed!

**Comment by kelson42** [comment]
Another CON: we go away from a well installed standard which is WARC.

**Comment by rgaudin** [comment]
> Another CON: we go away from a well installed standard which is WARC.

Updated my comment. WARC file is bundled into the WACZ so we _carry_ a standard file but indeed the solution would not be from a standard format to a ZIM but from a WACZ to a ZIM.

Both are documented *standards* of course but it's important to highlight that WARC is the well established and wide-spread one.
