### ISSUE TITLE
Document install procedure (was: Extremely long install with pip)

### ISSUE THREAD

**Issue by NielsGx** [openzim/warc2zim#89]
Hello,

I'm trying to install this with pip, but I'm already waiting for +30min, on a 2CPU 2GB RAM VPS
CPU is at 99%

`INFO: pip is looking at multiple versions of idna to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of charset-normalizer to determine which version is compatible with other requirements. This could take a while.
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.11-py3-none-any.whl (39 kB)
  Downloading charset_normalizer-2.0.10-py3-none-any.whl (39 kB)
  Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
  Downloading charset_normalizer-2.0.8-py3-none-any.whl (39 kB)
  Downloading charset_normalizer-2.0.7-py3-none-any.whl (38 kB)
  Downloading charset_normalizer-2.0.6-py3-none-any.whl (37 kB)
  Downloading charset_normalizer-2.0.5-py3-none-any.whl (37 kB)
  Downloading charset_normalizer-2.0.4-py3-none-any.whl (36 kB)
  Downloading charset_normalizer-2.0.3-py3-none-any.whl (35 kB)
  Downloading charset_normalizer-2.0.2-py3-none-any.whl (35 kB)
  Downloading charset_normalizer-2.0.1-py3-none-any.whl (35 kB)
  Downloading charset_normalizer-2.0.0-py3-none-any.whl (35 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking`

I tried to check the python backtracking documentation, but tbh I don't understand much

**Comment by kelson42** [comment]
@NielsGx what is the exact command you run? Do you run it in virtual env? what is your system? Would you be able please to upload the full log?

**Comment by NielsGx** [comment]
Uh, this is a fresh debian install, fresh python install, I just do pip install warc2zim, nothing special

I waited for 30-35min, then basically gave up, ctrl+c

**Comment by kelson42** [comment]
@rgaudin My feeling is that without a clear guidance through the local setup procedure, a few things can go wrong. This is what happen here probably and actually my own experience (many times) as a non python expert.

Like for many other scrapers, warc2zim would IMO benefit of a clear step by step install procedure within a venv.

I wonder as well if we (could) check a minmal version of Python?

**Comment by rgaudin** [comment]
@kelson42 minimum version is already in the metadata of the package.

I could reproduce the issue on a fresh debian. What happens is that debian:11 comes with python3.9 which libzim 0.1 (the one used in warc2zim) doesn't support. Pip tries to use the source package to build it but it goes into a circular dependency trying to install Cython as a build dependency.

If you can't wait for the next warc2zim release, you should install Python3.8 on your system. You can do it following [this guide](https://bgasparotto.com/install-pyenv-ubuntu-debian).

I tested the procedure and with the following two commands, warc2zim works fine:

```sh
apt install libmagic1
pip install "MarkupSafe==2.0.1"
```

Easier way would be to use openzim/zimit docker image which includes warc2zim.

**Comment by rgaudin** [comment]
New warc2zim 1.4.0 released.
