### ISSUE TITLE
Better non-working SW landing page

### ISSUE THREAD

**Issue by kelson42** [openzim/warc2zim#98]
This page is not good enough. People keep complaining that they don't know what to do.

**Comment by Jaifroid** [comment]
> I would propose to test in js if the https service is available and, if not, check if the service is reachable on 127.0.0.1. If found, then redirect automatically, didplay error otherwise.

At least for PCs, I would suggest testing first whether `http://localhost:[PORT]` is available, then http://127.0.0.1:[PORT]. For most average users `http://localhost` will be more intuitive and easier to remember.
